Option Strict Off
Option Explicit On
Module modConstants
	'=====================================================
	' Constant declaration for all vehicle objects
	'=====================================================
	' Subassemblies
	Public Const CLASSNAME_PROPERTY_ITEM As String = "Vehicles.cPropertyItem"
	Public Const CLASSNAME_VEHICLE As String = "Vehicles.cVehicle"
	Public Const CLASSNAME_GROUP As String = "Vehicles.cGroup"
	Public Const CLASSNAME_SURFACE As String = "Vehicles.cSurface"
	Public Const CLASSNAME_FEATURE As String = "Vehicles.cFeature"
	Public Const CLASSNAME_OPTIONS As String = "Vehicles.cOptions"
	Public Const CLASSNAME_STATS As String = "Vehicles.cStats"
	Public Const CLASSNAME_DESCRIPTION As String = "Vehicles.cDescription"
	Public Const CLASSNAME_CREW As String = "Vehicles.cCrew"
	Public Const CLASSNAME_AUTHOR As String = "Vehicles.cAuthor"
	
	Public Const CLASSNAME_BODY As String = "Vehicles.aBody"
	Public Const CLASSNAME_HAMMOCK As String = "Vehicles.aTest"
	
	'=====================================================
	' Interface ID's <-- cant be more than 32 (umm...  cuz of 32bitflag... but we'll see if this  holds up)
	'=====================================================
	Public Const INTERFACE_NODE As Short = 0 ' some of these ID's are purely abstract.
	Public Const INTERFACE_PERSIST As Short = 1
	Public Const INTERFACE_DISPLAY As Short = 2
	Public Const INTERFACE_BUILD As Short = 12
	
	Public Const INTERFACE_COMPONENT As Short = 4 ' this type is more of a classID and less of a interface
	Public Const INTERFACE_CONTAINER As Short = 5
	Public Const INTERFACE_SURFACE As Short = 6
	Public Const INTERFACE_FEATURE As Short = 11
	Public Const INTERFACE_VEHICLE As Short = 7
	Public Const INTERFACE_VEHICLE_DESCRIPTION As Short = 8
	Public Const INTERFACE_VEHICLE_VERSION As Short = 9
	Public Const INTERFACE_VEHICLE_AUTHOR As Short = 10
	
	Public Const INTERFACE_ARMOR As Short = 30
	Public Const INTERFACE_ARMOR_FACE As Short = 31
	Public Const INTERFACE_ARMOR_LAYER As Short = 32
	
	'=====================================================
	' Node Attribute Constants
	'=====================================================
	' there are 2^6 combinations so we should write a util (later to be merged into comp editor) that
	' will allow us to pick the attributes and it will produce the number we need to store in the XML def file
	Public Const NODE_REQUIRED As Short = 1 '(e.g. no user delete)
	Public Const NODE_FIXED As Short = 2 '(moveable within tree)
	Public Const NODE_VISIBLE As Short = 4 '
	Public Const NODE_RENAMEABLE As Short = 8 '
	Public Const NODE_COPYABLE As Short = 16 ' (node or branch - with a group, you shouldnt be able to save the group without any children though)
	Public Const NODE_SAVEABLE As Short = 32 '
	'Public Const NODE_PASTEABLE = 64& (actually if Copy is allowed, then goes to follow this would be allowed to IF the branch could accept children)
	
	'=====================================================
	' String Constants for drop down selections for various settings
	' Note: The constants must match precisely with the order of the drop down list items
	'       in the proplist items (which are loaded from the XML defs)
	'=====================================================
	Public Enum EMISSION_CLOAKING
		None = 0
		BASIC = 1
		RADICAL = 2
	End Enum
	
	
	
	Public Const Body As Short = 1
	Public Const Skid As Short = 2
	Public Const Wheel As Short = 3
	Public Const Track As Short = 4
	Public Const Leg As Short = 5
	Public Const Wing As Short = 6
	Public Const TTRotor As Short = 7
	Public Const Hydrofoil As Short = 8
	Public Const Hovercraft As Short = 9
	Public Const Superstructure As Short = 10
	Public Const OpenMount As Short = 11
	Public Const Mast As Short = 12
	Public Const Pod As Short = 13
	Public Const Turret As Short = 14
	Public Const Popturret As Short = 15
	Public Const Gasbag As Short = 16
	Public Const Arm As Short = 17
	
	' Other Pseudo Subs
	'Public Const Armor = 18
	Public Const Cargo As Short = 23
	Public Const equipmentPod As Short = 27
	Public Const SolarPanel As Short = 28
	Public Const SideCar As Short = 29
	Public Const ArmorOverall As Short = 30
	Public Const ArmorLocation As Short = 31
	Public Const ArmorBasicFacing As Short = 32
	Public Const ArmorComplexFacing As Short = 33
	Public Const ArmorGunShield As Short = 34
	Public Const ArmorWheelGuard As Short = 35
	Public Const ArmorOpenFrame As Short = 36
	Public Const SolarCellArray As Short = 37
	Public Const AutogyroRotor As Short = 38
	Public Const MMRotor As Short = 39
	Public Const CARotor As Short = 40
	Public Const ArmorComponent As Short = 41
	
	
	'Weapons and Weapon Accessories
	'Public Const ArtilleryandGun = 101
	'Public Const BeamWeapon = 102
	'Public Const Launcher = 103
	'Public Const TorpedoandMissile = 104
	Public Const WeaponLink As Short = 105
	Public Const PartialStabilizationGear As Short = 106
	Public Const FullStabilizationGear As Short = 111
	Public Const UniversalMount As Short = 107
	Public Const CasemateMount As Short = 112
	Public Const DoorMount As Short = 113
	Public Const Cyberslave As Short = 114
	Public Const WeaponBay As Short = 108
	Public Const AntiBlastMagazine As Short = 109
	Public Const HardPoint As Short = 110
	Public Const Ammunition As Short = 115
	Public Const BoltThrower As Short = 116
	Public Const StoneThrower As Short = 117
	Public Const RepeatingBoltThrower As Short = 118
	Public Const MuzzleLoader As Short = 119
	Public Const BreechLoader As Short = 120
	Public Const ManualRepeater As Short = 121
	Public Const Revolver As Short = 122
	Public Const MechanicalGatling As Short = 123
	Public Const SlowAutoloader As Short = 124
	Public Const FastAutoloader As Short = 125
	Public Const lightAutomatic As Short = 126
	Public Const HeavyAutomatic As Short = 127
	Public Const ElectricGatling As Short = 128
	
	
	Public Const Laser As Short = 129
	Public Const UVLaser As Short = 130
	Public Const IRLaser As Short = 131
	Public Const Disruptor As Short = 132
	Public Const ChargedParticleBeam As Short = 133
	Public Const NeutralParticleBeam As Short = 134
	Public Const Flamer As Short = 135
	Public Const Screamer As Short = 136
	Public Const Stunner As Short = 137
	Public Const ParalysisBeam As Short = 138
	Public Const XRayLaser As Short = 139
	Public Const FusionBeam As Short = 140
	Public Const GravityBeam As Short = 141
	Public Const AntiparticleBeam As Short = 142
	Public Const Graser As Short = 143
	Public Const Disintegrator As Short = 144
	Public Const Displacer As Short = 145
	Public Const BeamedPowerTransmitter As Short = 146
	Public Const MilitaryParalysisBeam As Short = 147
	'Public Const EnergyDrill = 624 'is already listed above in Heavy Equipt.
	Public Const DisposableLauncher As Short = 148
	Public Const MuzzleloadingLauncher As Short = 149
	Public Const BreechloadingLauncher As Short = 150
	Public Const ManualRepeaterLauncher As Short = 151
	Public Const SlowAutoLoaderLauncher As Short = 152
	Public Const FastAutoLoaderLauncher As Short = 153
	Public Const RevolverLauncher As Short = 154
	Public Const lightAutomaticLauncher As Short = 155
	Public Const HeavyAutomaticLauncher As Short = 156
	
	Public Const IronBomb As Short = 157
	Public Const RetardedBomb As Short = 158
	Public Const SmartBomb As Short = 159
	Public Const SelfDestructSystem As Short = 160
	Public Const ContactMine As Short = 161
	Public Const ProximityMine As Short = 162
	'Public Const AttackMine = 163 'removed since these should be built as vehicles themselves
	Public Const PressureTriggerMine As Short = 164
	Public Const CommandTriggerMine As Short = 165
	Public Const SmartTriggerMine As Short = 166
	'Public Const ParachuteMine = 167 'removed and added as option for  Comand and Smart Trigger mines
	Public Const UnGuidedMissile As Short = 168
	Public Const UnGuidedTorpedo As Short = 169
	Public Const GuidedMissile As Short = 170
	Public Const GuidedTorpedo As Short = 171
	Public Const RainbowLaser As Short = 172
	Public Const BlueGreenLaser As Short = 173
	Public Const FlameThrower As Short = 174
	Public Const WaterCannon As Short = 175
	
	' Propulsion
	Public Const WheeledDrivetrain As Short = 201
	Public Const AllWheelDriveWheeledDrivetrain As Short = 254
	Public Const TrackedDrivetrain As Short = 202
	Public Const LegDrivetrain As Short = 203
	Public Const FlexibodyDrivetrain As Short = 204
	Public Const TTRRotorDrivetrain As Short = 205
	Public Const MMRRotorDrivetrain As Short = 206
	Public Const CARRotorDrivetrain As Short = 207
	Public Const OrnithopterDrivetrain As Short = 208
	Public Const AerialPropeller As Short = 209
	Public Const DuctedFan As Short = 210
	Public Const PaddleWheel As Short = 211
	Public Const ScrewPropeller As Short = 212
	Public Const lightScrewPropeller As Short = 213
	Public Const DuctedPropeller As Short = 214
	Public Const Hydrojet As Short = 215
	Public Const MHDTunnel As Short = 216
	Public Const RopeHarness As Short = 217
	Public Const YokeandPoleHarness As Short = 218
	Public Const ShaftandCollarHarness As Short = 219
	Public Const WhiffletreeHarness As Short = 220
	Public Const RowingPositions As Short = 221
	Public Const SquareRig As Short = 222
	Public Const ForeandAftRig As Short = 255
	Public Const FullRig As Short = 256
	Public Const AerialSail As Short = 223
	Public Const lightSail As Short = 224
	Public Const MagLevLifter As Short = 225
	Public Const Turbojet As Short = 226
	Public Const Turbofan As Short = 227
	Public Const Ramjet As Short = 228
	Public Const TurboRamjet As Short = 229
	Public Const Hyperfan As Short = 230
	Public Const FusionAirRam As Short = 231
	Public Const StandardThruster As Short = 232
	Public Const SuperThruster As Short = 233
	Public Const MegaThruster As Short = 234
	Public Const LiquidFuelRocket As Short = 235
	Public Const MOXRocket As Short = 236
	Public Const IonDrive As Short = 237
	Public Const FissionRocket As Short = 238
	Public Const FusionRocket As Short = 239
	Public Const OptimizedFusion As Short = 240
	Public Const AntimatterThermal As Short = 241
	Public Const AntimatterPion As Short = 242
	Public Const OrionEngine As Short = 243
	Public Const SolidRocketEngine As Short = 244
	Public Const Hyperdrive As Short = 245
	Public Const JumpDrive As Short = 246
	Public Const WarpDrive As Short = 247
	Public Const TeleportationDrive As Short = 248
	Public Const SubQuantumConveyor As Short = 249
	Public Const ContraGravGenerator As Short = 250
	Public Const HotAir As Short = 251
	Public Const Hydrogen As Short = 252
	Public Const Helium As Short = 253
	Public Const ThrustBomb As Short = 257
	Public Const QuantumConveyor As Short = 258
	Public Const TwoQuantumConveyor As Short = 259
	Public Const AerialSailForeAftRig As Short = 260
	
	'Manned Vehicle Components
	Public Const PrimitiveManeuverControl As Short = 301
	Public Const MechanicalManeuverControl As Short = 302
	Public Const ElectronicManeuverControl As Short = 303
	Public Const ComputerizedManeuverControl As Short = 304
	'Public Const DuplicateMechanicalControl = 305
	'Public Const DuplicateElectronicControl = 306
	'Public Const DuplicateComputerizedControl = 307
	Public Const MechanicalDivingControl As Short = 308
	'Public Const DuplicateDivingControl = 309
	Public Const CrampedCrewStation As Short = 310 '
	Public Const NormalCrewStation As Short = 311
	Public Const RoomyCrewStation As Short = 312
	'Public Const ExposedCrewStation = 313 'this is just a user option
	Public Const CycleCrewStation As Short = 314
	Public Const HarnessCrewStation As Short = 315
	Public Const BattlesuitSystem As Short = 316
	Public Const FormFittingBattleSuitSystem As Short = 323
	Public Const CrampedSeat As Short = 317
	Public Const NormalSeat As Short = 318
	Public Const RoomySeat As Short = 319
	Public Const CrampedStandingRoom As Short = 320
	Public Const NormalStandingRoom As Short = 321
	Public Const RoomyStandingRoom As Short = 322
	'Public Const ExposedSeat = 323 'these are just options
	'Public Const ExposedStandingRoom = 324 'these are just options
	Public Const CycleSeat As Short = 325
	Public Const Hammock As Short = 326
	Public Const Bunk As Short = 327
	Public Const Cabin As Short = 328
	Public Const LuxuryCabin As Short = 329
	Public Const EnvironmentalControl As Short = 330
	Public Const NBCKit As Short = 331
	Public Const LimitedLifeSystem As Short = 332
	Public Const FullLifeSystem As Short = 333
	Public Const Provisions As Short = 334
	Public Const ArtificialGravityUnit As Short = 335
	Public Const EjectionSeat As Short = 336
	Public Const CrewEscapeCapsule As Short = 337
	Public Const Airbag As Short = 338
	Public Const CrashWeb As Short = 339
	' Public Const GSeat = 340 ' This is a property of Seats and CrewStations
	Public Const WombTank As Short = 341
	Public Const GravityWeb As Short = 342
	Public Const GravCompensator As Short = 343
	'Public Const BridgeAccessSpace = 344 'is now property of CrewStations
	Public Const SmallGalley As Short = 345
	Public Const ElectronicDivingControl As Short = 346
	Public Const ComputerizedDivingControl As Short = 347
	Public Const TotalLifeSystem As Short = 348
	Public Const Suite As Short = 349
	Public Const LuxurySuite As Short = 350
	'Power and Fuel
	Public Const MuscleEngine As Short = 401
	Public Const EarlySteamEngine As Short = 402
	Public Const ForcedDraftSteamEngine As Short = 403
	Public Const TripleExpansionSteamEngine As Short = 404
	Public Const SteamTurbine As Short = 405
	Public Const GasolineEngine As Short = 406
	Public Const HPGasolineEngine As Short = 407
	Public Const TurboGasolineEngine As Short = 408
	Public Const SuperGasolineEngine As Short = 409
	Public Const TurboHPGasolineEngine As Short = 410
	Public Const SuperHPGasolineEngine As Short = 411
	Public Const StandardDieselEngine As Short = 412
	Public Const TurboStandardDieselEngine As Short = 413
	Public Const MarineDieselEngine As Short = 414
	Public Const HPDieselEngine As Short = 416
	Public Const TurboHPDieselEngine As Short = 417
	Public Const NitrousOxideBooster As Short = 418
	Public Const Snorkel As Short = 419
	Public Const StandardGasTurbine As Short = 420
	Public Const HPGasTurbine As Short = 421
	Public Const OptimizedGasTurbine As Short = 422
	Public Const StandardMHDTurbine As Short = 423
	Public Const HPMHDTurbine As Short = 424
	Public Const FuelCell As Short = 425
	Public Const FissionReactor As Short = 426
	Public Const RTGReactor As Short = 427
	Public Const NPU As Short = 428
	Public Const FusionReactor As Short = 429
	Public Const AntimatterReactor As Short = 430
	Public Const TotalConversionPowerPlant As Short = 431
	Public Const CosmicPowerPlant As Short = 432
	Public Const Soulburner As Short = 433
	Public Const ElementalFurnace As Short = 435
	Public Const ManaEngine As Short = 436
	Public Const Carnivore As Short = 437
	Public Const Herbivore As Short = 438
	Public Const Omnivore As Short = 439
	Public Const Vampire As Short = 440
	Public Const ElectricContactPower As Short = 441
	Public Const LaserBeamedPowerReceiver As Short = 442
	Public Const MaserBeamedPowerReceiver As Short = 443
	Public Const ClockWork As Short = 444
	Public Const LeadAcidBattery As Short = 445
	Public Const AdvancedBattery As Short = 446
	Public Const Flywheel As Short = 447
	Public Const RechargeablePowerCell As Short = 448
	Public Const PowerCell As Short = 449
	Public Const CoalBunker As Short = 450
	Public Const WoodBunker As Short = 451
	Public Const StandardTank As Short = 452
	Public Const lightTank As Short = 453
	Public Const UltralightTank As Short = 454
	Public Const StandardSelfSealingTank As Short = 455
	Public Const lightSelfSealingTank As Short = 456
	Public Const UltralightSelfSealingTank As Short = 457
	Public Const Water As Short = 458
	Public Const Gasoline As Short = 459
	Public Const Diesel As Short = 460
	Public Const AviationGas As Short = 461
	Public Const JetFuel As Short = 462
	Public Const Propane As Short = 463
	Public Const LiquifiedNaturalGas As Short = 464
	Public Const EthanolAlchohol As Short = 465
	Public Const MethanolAlchohol As Short = 466
	Public Const LiquidHydrogen As Short = 467
	Public Const LiquidOxygen As Short = 468
	Public Const Cadmium As Short = 469
	Public Const MetalLOX As Short = 470
	Public Const RocketFuel As Short = 471
	Public Const AntiMatter As Short = 472
	Public Const AntiMatterBay As Short = 473
	Public Const CeramicEngine As Short = 474
	Public Const TurboCeramicEngine As Short = 475
	Public Const SuperCeramicEngine As Short = 476
	Public Const HPCeramicEngine As Short = 477
	Public Const TurboHPCeramicEngine As Short = 478
	Public Const SuperHPCeramicEngine As Short = 479
	Public Const HydrogenCombustionEngine As Short = 480
	Public Const Wood As Short = 481
	Public Const Coal As Short = 482
	Public Const UraniumFuelRod As Short = 483
	
	
	'Instruments and Electronics
	Public Const RadioCommunicator As Short = 5001
	Public Const TightBeamRadio As Short = 5002
	Public Const VLFRadio As Short = 5003
	Public Const CellularPhone As Short = 5004
	Public Const CellularPhonewithRadio As Short = 5005
	Public Const RadioJammer As Short = 5006
	Public Const ElfReceiver As Short = 5007
	Public Const LaserCommunicator As Short = 5008
	Public Const NeutrinoCommunicator As Short = 5009
	Public Const GravityRippleCommunicator As Short = 5010
	Public Const Headlight As Short = 5011
	Public Const Searchlight As Short = 5012
	Public Const InfraredSearchlight As Short = 5013
	Public Const Telescope As Short = 5014
	Public Const lightAmplification As Short = 5015
	Public Const LowlightTV As Short = 5016
	Public Const ExtendableSensorPeriscope As Short = 5017
	Public Const Radar As Short = 5018
	Public Const Ladar As Short = 5019
	Public Const ActiveSonar As Short = 5020
	Public Const PassiveSonar As Short = 5021
	Public Const PassiveInfrared As Short = 5022
	Public Const Thermograph As Short = 5023
	Public Const PassiveRadar As Short = 5024
	Public Const PESA As Short = 5025
	Public Const Geophone As Short = 5026
	Public Const MAD As Short = 5027
	Public Const MultiScanner As Short = 5028
	Public Const ChemScanner As Short = 5029
	Public Const RadScanner As Short = 5030
	Public Const BioScanner As Short = 5031
	Public Const GravScanner As Short = 5032
	Public Const RangingSoundDetector As Short = 5033
	Public Const MeteorologicalInstruments As Short = 5034
	'Public Const AstronomicalTelescope = 5035 'user now builds these like normal telescopes and adds stabilization
	Public Const AstronomicalInstruments As Short = 5036
	Public Const LowResPlanetarySurveyArray As Short = 5037
	Public Const MedResPlanetarySurveyArray As Short = 5038
	Public Const HighResPlanetarySurveyArray As Short = 5039
	Public Const SoundSystem As Short = 5040
	Public Const FlightRecorder As Short = 5041
	Public Const VehicleCamera As Short = 5042
	Public Const DigitalVehicleCamera As Short = 5043
	Public Const ReconCamera As Short = 5044
	Public Const DigitalReconCamera As Short = 5045
	'Public Const InfraredCamera = 5046 'these are now hardcoded and not read from table
	'Public Const LowlightCamera = 5047  'these are now hardcoded and not read from table
	Public Const NavigationInstruments As Short = 5048
	'Public Const PrecisionNavigationInstruments = 5049 'hardcoded option
	Public Const NavigationalRadar As Short = 5050
	Public Const AntiCollisionRadar As Short = 5051
	Public Const AutoPilot As Short = 5052
	Public Const IFF As Short = 5053
	Public Const Transponder As Short = 5054
	Public Const INS As Short = 5055
	Public Const GPS As Short = 5056
	Public Const MilitaryGPS As Short = 5057
	Public Const TFR As Short = 5058
	Public Const OpticalBombSight As Short = 5059
	Public Const FireDirectionCenter As Short = 5060
	Public Const HUDWAC As Short = 5061
	Public Const PupilHUDWAC As Short = 5062
	Public Const LaserRangeFinder As Short = 5063
	Public Const LaserDesignator As Short = 5064
	Public Const LaserSpotTracker As Short = 5065
	Public Const RadarDetector As Short = 5066
	'Public Const AdvancedRadarDetector = 5067 'hardcoded option
	Public Const LaserSensor As Short = 5068
	Public Const LaserRadarDetector As Short = 5069
	'Public Const AdvancedLaserRadarDetector = 5070 'hardcoded option
	Public Const RadioDirectionFinder As Short = 5071
	Public Const AreaRadarJammer As Short = 5072
	Public Const DeceptiveRadarJammer As Short = 5073
	Public Const InfraredJammer As Short = 5074
	Public Const ChaffDecoyDischarger As Short = 5075
	Public Const RadarReflector As Short = 5076
	Public Const BlipEnhancer As Short = 5077
	Public Const TEMPEST As Short = 5078
	Public Const MacroFrame As Short = 5079
	Public Const MainFrame As Short = 5080
	Public Const MicroFrame As Short = 5081
	Public Const MiniComputer As Short = 5082
	Public Const SmallComputer As Short = 5083
	Public Const Terminal As Short = 5084
	Public Const FireDirectionSoftware As Short = 5085
	Public Const DatabaseSoftware As Short = 5086
	Public Const CartographySoftware As Short = 5087
	Public Const ComputerNavigationSoftware As Short = 5088
	Public Const DatalinkSoftware As Short = 5089
	Public Const TargetingSoftware As Short = 5090
	Public Const TransmissionProfilingSoftware As Short = 5091
	Public Const GunnerSoftware As Short = 5092
	Public Const DamageControlSoftware As Short = 5093
	Public Const PersonalitySimulationSoftwareFull As Short = 5094
	Public Const RobotSkillProgramsPhysical As Short = 5095
	Public Const RoutineVehicleOperationSoftwarePilot As Short = 5096
	Public Const SurgicalInterface As Short = 5097
	Public Const InterfaceWeb As Short = 5098
	Public Const AutoInterfaceWeb As Short = 5099
	Public Const SocketInterface As Short = 5100
	Public Const NeuralInductionField As Short = 5101
	Public Const ImprovedOpticalBombSight As Short = 5102
	Public Const AdvancedOpticalBombSight As Short = 5103
	Public Const PersonalitySimulationLimited As Short = 5104
	Public Const RoutineVehicleOperationSoftwareOther As Short = 5105
	Public Const SurveillanceSoundDetector As Short = 5106
	Public Const RobotSkillProgramsMental As Short = 5107
	Public Const HoloventureProgram As Short = 5108
	Public Const LowResImagingRadar As Short = 5109
	Public Const HiResImagingRadar As Short = 5110
	Public Const AESA As Short = 5111
	Public Const DecoyChaff As Short = 5112
	Public Const DecoySmoke As Short = 5113
	Public Const DecoyFlares As Short = 5114
	Public Const DecoySonarDecoy As Short = 5115
	Public Const DecoyHotSmoke As Short = 5116
	Public Const DecoyPrism As Short = 5117
	Public Const DecoyBlackOutGas As Short = 5118
	Public Const SmokeDecoyDischarger As Short = 5119
	Public Const FlareDecoyDischarger As Short = 5120
	Public Const SonarDecoyDischarger As Short = 5121
	Public Const HotSmokeDecoyDischarger As Short = 5122
	Public Const PrismDecoyDischarger As Short = 5123
	Public Const BlackOutGasDecoyDischarger As Short = 5124
	Public Const DeflectorField As Short = 5125
	Public Const ForceScreen As Short = 5126
	Public Const VariableForceScreen As Short = 5127
	
	'Miscellaneous equipment
	Public Const ArmMotor As Short = 601
	Public Const FireExtinguisherSystem As Short = 602
	Public Const FullFireSuppressionSystem As Short = 603
	Public Const CompactFireSuppressionSystem As Short = 604
	Public Const BilgePump As Short = 605
	Public Const CompleteWorkshop As Short = 606
	Public Const MechanicWorkshop As Short = 607
	Public Const EngineeringWorkshop As Short = 608
	Public Const ElectronicsWorkshop As Short = 609
	Public Const ArmouryWorkshop As Short = 610
	Public Const CompleteMiniWorkshop As Short = 611
	Public Const ScienceLab As Short = 612 'LOOKUP SKILLS IN BASIC SET 59-62
	Public Const ExtendableLadder As Short = 613
	Public Const Crane As Short = 614
	Public Const Winch As Short = 615
	Public Const PowerShovel As Short = 616
	Public Const WreckingCrane As Short = 617
	Public Const ForkLift As Short = 618
	Public Const VehicularBridge As Short = 619
	Public Const LaunchCatapult As Short = 620
	Public Const SkyHook As Short = 621
	Public Const Bore As Short = 622
	Public Const SuperBore As Short = 623
	Public Const EnergyDrill As Short = 624
	Public Const TractorBeam As Short = 625
	Public Const PressorBeam As Short = 626
	Public Const OperatingRoom As Short = 627
	Public Const StretcherPallet As Short = 628
	Public Const EmergencySupportUnit As Short = 629
	Public Const EmergencylightsandSiren As Short = 630
	Public Const CryonicCapsule As Short = 631
	Public Const Automed As Short = 632
	Public Const DiagnosisTable As Short = 633
	Public Const Stage As Short = 634
	Public Const Hall As Short = 635
	Public Const BarRoom As Short = 636
	Public Const ConferenceRoom As Short = 637
	'Public Const SwimmingPool = 638 'user must build this themselves
	Public Const MovieScreenandProjector As Short = 639
	Public Const MovieScreenandProjectorSmall As Short = 640
	Public Const HoloventureZone As Short = 641
	'Public Const NeuralInterfaceEntertainment = 642
	'Public Const Door = 643
	'Public Const Hatch = 644
	Public Const CargoRamp As Short = 645
	Public Const Airlock As Short = 646
	Public Const MembraneAirlock As Short = 647
	Public Const Forcelock As Short = 648
	Public Const PassageTube As Short = 649
	Public Const TeleportProjector As Short = 650
	Public Const BrigsandRestraints As Short = 651
	Public Const BurglarAlarm As Short = 652
	Public Const HighSecurityAlarm As Short = 653
	Public Const MutableLicensePlate As Short = 655
	Public Const OilSprayer As Short = 656
	Public Const PaintSprayer As Short = 657
	Public Const SmokeScreen As Short = 659
	Public Const SpikeDropper As Short = 660
	Public Const VehicleBay As Short = 661
	Public Const HangerBay As Short = 662
	Public Const DryDock As Short = 663
	Public Const SpaceDock As Short = 664
	Public Const ExternalCradle As Short = 665
	Public Const ArrestorHook As Short = 666
	Public Const VehicularParachute As Short = 667
	Public Const RefuellingProbe As Short = 668
	Public Const RefuellingDrogue As Short = 669
	Public Const FuelElectrolysisSystem As Short = 670
	Public Const HydrogenFuelScoop As Short = 671
	Public Const AtmosphereProcessor As Short = 672
	Public Const NuclearDamper As Short = 673
	Public Const SmallRealityStabilizer As Short = 674
	Public Const ModularSocket As Short = 675
	'UPGRADE_NOTE: Module was upgraded to Module_Renamed. Click for more: 'ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?keyword="A9E4979A-37FA-4718-9994-97DD76ED70A7"'
	Public Const Module_Renamed As Short = 676
	Public Const MiniMechanicWorkshop As Short = 677
	Public Const CombinationBeam As Short = 678
	Public Const ArmoredPassageTube As Short = 679
	Public Const MediumRealityStabilizer As Short = 680
	Public Const HeavyRealityStabilizer As Short = 681
	Public Const CraneWithElectroMagnet As Short = 682
	Public Const MiniElectronicsWorkshop As Short = 683
	Public Const MiniEngineeringWorkshop As Short = 684
	Public Const MiniArmouryWorkshop As Short = 685
	
	' PERFORMANCE PROFILES
	Public Const PERFORMANCEPROFILE As Short = 999
	Public Const PERFORMANCEAIR As Short = 980
	Public Const PERFORMANCEHOVER As Short = 981
	Public Const PERFORMANCEMAGLEV As Short = 982
	Public Const PERFORMANCEWATER As Short = 983
	Public Const PERFORMANCESUB As Short = 984
	Public Const PERFORMANCELEG As Short = 985
	Public Const PERFORMANCETRACK As Short = 986
	Public Const PERFORMANCEWHEEL As Short = 987
	Public Const PERFORMANCEFLEX As Short = 988
	Public Const PERFORMANCESKID As Short = 989
	Public Const PERFORMANCESPACE As Short = 990
	
	' CUSTOM AND CONTAINERS
	Public Const SimpleCustom As Short = 1000
	Public Const GroupComponent As Short = 1100
	
	' Key Constants for some special tree node types (uses 1200 series data type values)
	Public Const VEHICLE_NODE As Short = 1200 'linked to clsStats
	'Public Const SETTINGS_NODE = 1201         'linked to clsSettings
	'Public Const SURFACE_NODE = 1202          'linked to clsSurface
	'Public Const OPTIONS_NODE = 1203          'linked to clsOptions - Stats only since these options like swept wings and snow tires are set elsewhere
	' also stuff like cargo weight, access space mods etc
	'Public Const DESCRIPTION_NODE = 1204      ' linked to clsDescription
	Public Const CREW_NODE As Short = 1205
	
	Public Const PERFORMANCE_NODE As Short = 1206 ' linked to  NOTHING?
	Public Const POWERSYSTEMS_NODE As Short = 1207 ' linked to NOTHING?
	Public Const WEAPON_LINKS_NODE As Short = 1208 ' linked to NOTHING?
	Public Const FUELSYSTEMS_NODE As Short = 1209 ' linked to NOTHING?
	
	
	Public Const BODY_KEY As String = "1_" ' linked to clsBody
	
	' Reserved Keys for Battlesuits
	Public Const BATTLESUIT_KEY_SYSTEM As String = "2_"
	Public Const BATTLESUIT_KEY_HEAD As String = "3_"
	Public Const BATTLESUIT_KEY_LEFT_ARM As String = "4_"
	Public Const BATTLESUIT_KEY_LEFT_ARM_MOTOR As String = "5_"
	Public Const BATTLESUIT_KEY_RIGHT_ARM As String = "6_"
	Public Const BATTLESUIT_KEY_RIGHT_ARM_MOTOR As String = "7_"
	Public Const BATTLESUIT_KEY_LEFT_LEG As String = "8_"
	Public Const BATTLESUIT_KEY_LEFT_LEG_MOTOR As String = "9_"
	Public Const BATTLESUIT_KEY_RIGHT_LEG As String = "10_"
	Public Const BATTLESUIT_KEY_RIGHT_LEG_MOTOR As String = "11_"
	
	' Reserved Keys for Default Nodes
	'Public Const VEHICLE_KEY = "0_"          'linked to clsStats
	'Public Const SETTINGS_KEY = "12_"         'linked to clsSettings
	'Public Const SURFACE_KEY = "13_"          'linked to clsSurface
	'Public Const OPTIONS_KEY = "14_"          'linked to clsOptions - Stats only since these options like swept wings and snow tires are set elsewhere
	' also stuff like cargo weight, access space mods etc
	Public Const DESCRIPTION_KEY As String = "DKEY" ' linked to clsDescription
	Public Const CREW_KEY As String = "CKEY"
	
	Public Const PERFORMANCE_KEY As String = "PKEY" ' linked to  NOTHING?
	Public Const POWERSYSTEMS_KEY As String = "PWKEY" ' linked to NOTHING?
	Public Const WEAPON_LINKS_KEY As String = "WLKEY" ' linked to NOTHING?
	Public Const FUELSYSTEMS_KEY As String = "FKEY" ' linked to NOTHING?
	
	Public Const GROUP_NAME As String = "Group"
	Public Const CHILD_GROUP_NAME As String = "Child Group"
	
	
	' Constants for Checklist and TreeX view modes
	Public Const FUEL_PROFILE As Short = 1
	Public Const POWER_PROFILE As Short = 2
	Public Const WEAPON_CHECKLIST As Short = 1
	Public Const PERFORMANCE_CHECKLIST As Short = 2
	
	''=====================================================
	'' Constant declaration for all vehicle objects
	''=====================================================
	'' Subassemblies
	'Public Const Body = 1
	'Public Const Skid = 2
	'Public Const Wheel = 3
	'Public Const Track = 4
	'Public Const Leg = 5
	'Public Const Wing = 6
	'Public Const TTRotor = 7
	'Public Const Hydrofoil = 8
	'Public Const Hovercraft = 9
	'Public Const Superstructure = 10
	'Public Const OpenMount = 11
	'Public Const Mast = 12
	'Public Const Pod = 13
	'Public Const Turret = 14
	'Public Const Popturret = 15
	'Public Const Gasbag = 16
	'Public Const Arm = 17
	'' Other Pseudo Subs
	''Public Const Armor = 18
	'Public Const Cargo = 23
	'Public Const equipmentPod = 27
	'Public Const SolarPanel = 28
	'Public Const SideCar = 29
	'Public Const ArmorOverall = 30
	'Public Const ArmorLocation = 31
	'Public Const ArmorBasicFacing = 32
	'Public Const ArmorComplexFacing = 33
	'Public Const ArmorGunShield = 34
	'Public Const ArmorWheelGuard = 35
	'Public Const ArmorOpenFrame = 36
	'Public Const SolarCellArray = 37
	'Public Const AutogyroRotor = 38
	'Public Const MMRotor = 39
	'Public Const CARotor = 40
	'Public Const ArmorComponent = 41
	'
	''Instruments and Electronics
	'Public Const RadioCommunicator = 5001
	'Public Const TightBeamRadio = 5002
	'Public Const VLFRadio = 5003
	'Public Const CellularPhone = 5004
	'Public Const CellularPhonewithRadio = 5005
	'Public Const RadioJammer = 5006
	'Public Const ElfReceiver = 5007
	'Public Const LaserCommunicator = 5008
	'Public Const NeutrinoCommunicator = 5009
	'Public Const GravityRippleCommunicator = 5010
	'Public Const Headlight = 5011
	'Public Const Searchlight = 5012
	'Public Const InfraredSearchlight = 5013
	'Public Const Telescope = 5014
	'Public Const lightAmplification = 5015
	'Public Const LowlightTV = 5016
	'Public Const ExtendableSensorPeriscope = 5017
	'Public Const Radar = 5018
	'Public Const Ladar = 5019
	'Public Const ActiveSonar = 5020
	'Public Const PassiveSonar = 5021
	'Public Const PassiveInfrared = 5022
	'Public Const Thermograph = 5023
	'Public Const PassiveRadar = 5024
	'Public Const PESA = 5025
	'Public Const Geophone = 5026
	'Public Const MAD = 5027
	'Public Const MultiScanner = 5028
	'Public Const ChemScanner = 5029
	'Public Const RadScanner = 5030
	'Public Const BioScanner = 5031
	'Public Const GravScanner = 5032
	'Public Const RangingSoundDetector = 5033
	'Public Const MeteorologicalInstruments = 5034
	''Public Const AstronomicalTelescope = 5035 'user now builds these like normal telescopes and adds stabilization
	'Public Const AstronomicalInstruments = 5036
	'Public Const LowResPlanetarySurveyArray = 5037
	'Public Const MedResPlanetarySurveyArray = 5038
	'Public Const HighResPlanetarySurveyArray = 5039
	'Public Const SoundSystem = 5040
	'Public Const FlightRecorder = 5041
	'Public Const VehicleCamera = 5042
	'Public Const DigitalVehicleCamera = 5043
	'Public Const ReconCamera = 5044
	'Public Const DigitalReconCamera = 5045
	''Public Const InfraredCamera = 5046 'these are now hardcoded and not read from table
	''Public Const LowlightCamera = 5047  'these are now hardcoded and not read from table
	'Public Const NavigationInstruments = 5048
	''Public Const PrecisionNavigationInstruments = 5049 'hardcoded option
	'Public Const NavigationalRadar = 5050
	'Public Const AntiCollisionRadar = 5051
	'Public Const AutoPilot = 5052
	'Public Const IFF = 5053
	'Public Const Transponder = 5054
	'Public Const INS = 5055
	'Public Const GPS = 5056
	'Public Const MilitaryGPS = 5057
	'Public Const TFR = 5058
	'Public Const OpticalBombSight = 5059
	'Public Const FireDirectionCenter = 5060
	'Public Const HUDWAC = 5061
	'Public Const PupilHUDWAC = 5062
	'Public Const LaserRangeFinder = 5063
	'Public Const LaserDesignator = 5064
	'Public Const LaserSpotTracker = 5065
	'Public Const RadarDetector = 5066
	''Public Const AdvancedRadarDetector = 5067 'hardcoded option
	'Public Const LaserSensor = 5068
	'Public Const LaserRadarDetector = 5069
	''Public Const AdvancedLaserRadarDetector = 5070 'hardcoded option
	'Public Const RadioDirectionFinder = 5071
	'Public Const AreaRadarJammer = 5072
	'Public Const DeceptiveRadarJammer = 5073
	'Public Const InfraredJammer = 5074
	'Public Const ChaffDecoyDischarger = 5075
	'Public Const RadarReflector = 5076
	'Public Const BlipEnhancer = 5077
	'Public Const TEMPEST = 5078
	'Public Const MacroFrame = 5079
	'Public Const MainFrame = 5080
	'Public Const MicroFrame = 5081
	'Public Const MiniComputer = 5082
	'Public Const SmallComputer = 5083
	'Public Const Terminal = 5084
	'Public Const FireDirectionSoftware = 5085
	'Public Const DatabaseSoftware = 5086
	'Public Const CartographySoftware = 5087
	'Public Const ComputerNavigationSoftware = 5088
	'Public Const DatalinkSoftware = 5089
	'Public Const TargetingSoftware = 5090
	'Public Const TransmissionProfilingSoftware = 5091
	'Public Const GunnerSoftware = 5092
	'Public Const DamageControlSoftware = 5093
	'Public Const PersonalitySimulationSoftwareFull = 5094
	'Public Const RobotSkillProgramsPhysical = 5095
	'Public Const RoutineVehicleOperationSoftwarePilot = 5096
	'Public Const SurgicalInterface = 5097
	'Public Const InterfaceWeb = 5098
	'Public Const AutoInterfaceWeb = 5099
	'Public Const SocketInterface = 5100
	'Public Const NeuralInductionField = 5101
	'Public Const ImprovedOpticalBombSight = 5102
	'Public Const AdvancedOpticalBombSight = 5103
	'Public Const PersonalitySimulationLimited = 5104
	'Public Const RoutineVehicleOperationSoftwareOther = 5105
	'Public Const SurveillanceSoundDetector = 5106
	'Public Const RobotSkillProgramsMental = 5107
	'Public Const HoloventureProgram = 5108
	'Public Const LowResImagingRadar = 5109
	'Public Const HiResImagingRadar = 5110
	'Public Const AESA = 5111
	'Public Const DecoyChaff = 5112
	'Public Const DecoySmoke = 5113
	'Public Const DecoyFlares = 5114
	'Public Const DecoySonarDecoy = 5115
	'Public Const DecoyHotSmoke = 5116
	'Public Const DecoyPrism = 5117
	'Public Const DecoyBlackOutGas = 5118
	'Public Const SmokeDecoyDischarger = 5119
	'Public Const FlareDecoyDischarger = 5120
	'Public Const SonarDecoyDischarger = 5121
	'Public Const HotSmokeDecoyDischarger = 5122
	'Public Const PrismDecoyDischarger = 5123
	'Public Const BlackOutGasDecoyDischarger = 5124
	'Public Const DeflectorField = 5125
	'Public Const ForceScreen = 5126
	'Public Const VariableForceScreen = 5127
	'
	''Miscellaneous equipment
	'Public Const ArmMotor = 601
	'Public Const FireExtinguisherSystem = 602
	'Public Const FullFireSuppressionSystem = 603
	'Public Const CompactFireSuppressionSystem = 604
	'Public Const BilgePump = 605
	'Public Const CompleteWorkshop = 606
	'Public Const MechanicWorkshop = 607
	'Public Const EngineeringWorkshop = 608
	'Public Const ElectronicsWorkshop = 609
	'Public Const ArmouryWorkshop = 610
	'Public Const CompleteMiniWorkshop = 611
	'Public Const ScienceLab = 612  'LOOKUP SKILLS IN BASIC SET 59-62
	'Public Const ExtendableLadder = 613
	'Public Const Crane = 614
	'Public Const Winch = 615
	'Public Const PowerShovel = 616
	'Public Const WreckingCrane = 617
	'Public Const ForkLift = 618
	'Public Const VehicularBridge = 619
	'Public Const LaunchCatapult = 620
	'Public Const SkyHook = 621
	'Public Const Bore = 622
	'Public Const SuperBore = 623
	'Public Const TractorBeam = 625
	'Public Const PressorBeam = 626
	'Public Const OperatingRoom = 627
	'Public Const StretcherPallet = 628
	'Public Const EmergencySupportUnit = 629
	'Public Const EmergencylightsandSiren = 630
	'Public Const CryonicCapsule = 631
	'Public Const Automed = 632
	'Public Const DiagnosisTable = 633
	'Public Const Stage = 634
	'Public Const Hall = 635
	'Public Const BarRoom = 636
	'Public Const ConferenceRoom = 637
	''Public Const SwimmingPool = 638 'user must build this themselves
	'Public Const MovieScreenandProjector = 639
	'Public Const MovieScreenandProjectorSmall = 640
	'Public Const HoloventureZone = 641
	''Public Const NeuralInterfaceEntertainment = 642
	''Public Const Door = 643
	''Public Const Hatch = 644
	'Public Const CargoRamp = 645
	'Public Const Airlock = 646
	'Public Const MembraneAirlock = 647
	'Public Const Forcelock = 648
	'Public Const PassageTube = 649
	'Public Const TeleportProjector = 650
	'Public Const BrigsandRestraints = 651
	'Public Const BurglarAlarm = 652
	'Public Const HighSecurityAlarm = 653
	'Public Const MutableLicensePlate = 655
	'Public Const OilSprayer = 656
	'Public Const PaintSprayer = 657
	'Public Const SmokeScreen = 659
	'Public Const SpikeDropper = 660
	'Public Const VehicleBay = 661
	'Public Const HangerBay = 662
	'Public Const DryDock = 663
	'Public Const SpaceDock = 664
	'Public Const ExternalCradle = 665
	'Public Const ArrestorHook = 666
	'Public Const VehicularParachute = 667
	'Public Const RefuellingProbe = 668
	'Public Const RefuellingDrogue = 669
	'Public Const FuelElectrolysisSystem = 670
	'Public Const HydrogenFuelScoop = 671
	'Public Const AtmosphereProcessor = 672
	'Public Const NuclearDamper = 673
	'Public Const SmallRealityStabilizer = 674
	'Public Const ModularSocket = 675
	'Public Const Module = 676
	'Public Const MiniMechanicWorkshop = 677
	'Public Const CombinationBeam = 678
	'Public Const ArmoredPassageTube = 679
	'Public Const MediumRealityStabilizer = 680
	'Public Const HeavyRealityStabilizer = 681
	'Public Const CraneWithElectroMagnet = 682
	'Public Const MiniElectronicsWorkshop = 683
	'Public Const MiniEngineeringWorkshop = 684
	'Public Const MiniArmouryWorkshop = 685
	'
	''Manned Vehicle Components
	'Public Const PrimitiveManeuverControl = 301
	'Public Const MechanicalManeuverControl = 302
	'Public Const ElectronicManeuverControl = 303
	'Public Const ComputerizedManeuverControl = 304
	''Public Const DuplicateMechanicalControl = 305
	''Public Const DuplicateElectronicControl = 306
	''Public Const DuplicateComputerizedControl = 307
	'Public Const MechanicalDivingControl = 308
	''Public Const DuplicateDivingControl = 309
	'Public Const CrampedCrewStation = 310 '
	'Public Const NormalCrewStation = 311
	'Public Const RoomyCrewStation = 312
	''Public Const ExposedCrewStation = 313 'this is just a user option
	'Public Const CycleCrewStation = 314
	'Public Const HarnessCrewStation = 315
	'Public Const BattlesuitSystem = 316
	'Public Const FormFittingBattleSuitSystem = 323
	'Public Const CrampedSeat = 317
	'Public Const NormalSeat = 318
	'Public Const RoomySeat = 319
	'Public Const CrampedStandingRoom = 320
	'Public Const NormalStandingRoom = 321
	'Public Const RoomyStandingRoom = 322
	''Public Const ExposedSeat = 323 'these are just options
	''Public Const ExposedStandingRoom = 324 'these are just options
	'Public Const CycleSeat = 325
	'Public Const Hammock = 326
	'Public Const Bunk = 327
	'Public Const Cabin = 328
	'Public Const LuxuryCabin = 329
	'Public Const EnvironmentalControl = 330
	'Public Const NBCKit = 331
	'Public Const LimitedLifeSystem = 332
	'Public Const FullLifeSystem = 333
	'Public Const Provisions = 334
	'Public Const ArtificialGravityUnit = 335
	'Public Const EjectionSeat = 336
	'Public Const CrewEscapeCapsule = 337
	'Public Const Airbag = 338
	'Public Const CrashWeb = 339
	'' Public Const GSeat = 340 ' This is a property of Seats and CrewStations
	'Public Const WombTank = 341
	'Public Const GravityWeb = 342
	'Public Const GravCompensator = 343
	''Public Const BridgeAccessSpace = 344 'is now property of CrewStations
	'Public Const SmallGalley = 345
	'Public Const ElectronicDivingControl = 346
	'Public Const ComputerizedDivingControl = 347
	'Public Const TotalLifeSystem = 348
	'Public Const Suite = 349
	'Public Const LuxurySuite = 350
	''Power and Fuel
	'Public Const MuscleEngine = 401
	'Public Const EarlySteamEngine = 402
	'Public Const ForcedDraftSteamEngine = 403
	'Public Const TripleExpansionSteamEngine = 404
	'Public Const SteamTurbine = 405
	'Public Const GasolineEngine = 406
	'Public Const HPGasolineEngine = 407
	'Public Const TurboGasolineEngine = 408
	'Public Const SuperGasolineEngine = 409
	'Public Const TurboHPGasolineEngine = 410
	'Public Const SuperHPGasolineEngine = 411
	'Public Const StandardDieselEngine = 412
	'Public Const TurboStandardDieselEngine = 413
	'Public Const MarineDieselEngine = 414
	'Public Const HPDieselEngine = 416
	'Public Const TurboHPDieselEngine = 417
	'Public Const NitrousOxideBooster = 418
	'Public Const Snorkel = 419
	'Public Const StandardGasTurbine = 420
	'Public Const HPGasTurbine = 421
	'Public Const OptimizedGasTurbine = 422
	'Public Const StandardMHDTurbine = 423
	'Public Const HPMHDTurbine = 424
	'Public Const FuelCell = 425
	'Public Const FissionReactor = 426
	'Public Const RTGReactor = 427
	'Public Const NPU = 428
	'Public Const FusionReactor = 429
	'Public Const AntimatterReactor = 430
	'Public Const TotalConversionPowerPlant = 431
	'Public Const CosmicPowerPlant = 432
	'Public Const Soulburner = 433
	'Public Const ElementalFurnace = 435
	'Public Const ManaEngine = 436
	'Public Const Carnivore = 437
	'Public Const Herbivore = 438
	'Public Const Omnivore = 439
	'Public Const Vampire = 440
	'Public Const ElectricContactPower = 441
	'Public Const LaserBeamedPowerReceiver = 442
	'Public Const MaserBeamedPowerReceiver = 443
	'Public Const ClockWork = 444
	'Public Const LeadAcidBattery = 445
	'Public Const AdvancedBattery = 446
	'Public Const Flywheel = 447
	'Public Const RechargeablePowerCell = 448
	'Public Const PowerCell = 449
	'Public Const CoalBunker = 450
	'Public Const WoodBunker = 451
	'Public Const StandardTank = 452
	'Public Const lightTank = 453
	'Public Const UltralightTank = 454
	'Public Const StandardSelfSealingTank = 455
	'Public Const lightSelfSealingTank = 456
	'Public Const UltralightSelfSealingTank = 457
	'Public Const Water = 458
	'Public Const Gasoline = 459
	'Public Const Diesel = 460
	'Public Const AviationGas = 461
	'Public Const JetFuel = 462
	'Public Const Propane = 463
	'Public Const LiquifiedNaturalGas = 464
	'Public Const EthanolAlchohol = 465
	'Public Const MethanolAlchohol = 466
	'Public Const LiquidHydrogen = 467
	'Public Const LiquidOxygen = 468
	'Public Const Cadmium = 469
	'Public Const MetalLOX = 470
	'Public Const RocketFuel = 471
	'Public Const AntiMatter = 472
	'Public Const AntiMatterBay = 473
	'Public Const CeramicEngine = 474
	'Public Const TurboCeramicEngine = 475
	'Public Const SuperCeramicEngine = 476
	'Public Const HPCeramicEngine = 477
	'Public Const TurboHPCeramicEngine = 478
	'Public Const SuperHPCeramicEngine = 479
	'Public Const HydrogenCombustionEngine = 480
	'Public Const Wood = 481
	'Public Const Coal = 482
	'Public Const UraniumFuelRod = 483
	''Weapons and Weapon Accessories
	''Public Const ArtilleryandGun = 101
	''Public Const BeamWeapon = 102
	''Public Const Launcher = 103
	''Public Const TorpedoandMissile = 104
	'Public Const WeaponLink = 105
	'Public Const PartialStabilizationGear = 106
	'Public Const FullStabilizationGear = 111
	'Public Const UniversalMount = 107
	'Public Const CasemateMount = 112
	'Public Const DoorMount = 113
	'Public Const Cyberslave = 114
	'Public Const WeaponBay = 108
	'Public Const AntiBlastMagazine = 109
	'Public Const HardPoint = 110
	'Public Const Ammunition = 115
	'Public Const BoltThrower = 116
	'Public Const StoneThrower = 117
	'Public Const RepeatingBoltThrower = 118
	'Public Const MuzzleLoader = 119
	'Public Const BreechLoader = 120
	'Public Const ManualRepeater = 121
	'Public Const Revolver = 122
	'Public Const MechanicalGatling = 123
	'Public Const SlowAutoloader = 124
	'Public Const FastAutoloader = 125
	'Public Const lightAutomatic = 126
	'Public Const HeavyAutomatic = 127
	'Public Const ElectricGatling = 128
	'
	'
	'Public Const Laser = 129
	'Public Const UVLaser = 130
	'Public Const IRLaser = 131
	'Public Const Disruptor = 132
	'Public Const ChargedParticleBeam = 133
	'Public Const NeutralParticleBeam = 134
	'Public Const Flamer = 135
	'Public Const Screamer = 136
	'Public Const Stunner = 137
	'Public Const ParalysisBeam = 138
	'Public Const XRayLaser = 139
	'Public Const FusionBeam = 140
	'Public Const GravityBeam = 141
	'Public Const AntiparticleBeam = 142
	'Public Const Graser = 143
	'Public Const Disintegrator = 144
	'Public Const Displacer = 145
	'Public Const BeamedPowerTransmitter = 146
	'Public Const MilitaryParalysisBeam = 147
	'Public Const DisposableLauncher = 148
	'Public Const MuzzleloadingLauncher = 149
	'Public Const BreechloadingLauncher = 150
	'Public Const ManualRepeaterLauncher = 151
	'Public Const SlowAutoLoaderLauncher = 152
	'Public Const FastAutoLoaderLauncher = 153
	'Public Const RevolverLauncher = 154
	'Public Const lightAutomaticLauncher = 155
	'Public Const HeavyAutomaticLauncher = 156
	'
	'Public Const IronBomb = 157
	'Public Const RetardedBomb = 158
	'Public Const SmartBomb = 159
	'Public Const SelfDestructSystem = 160
	'Public Const ContactMine = 161
	'Public Const ProximityMine = 162
	''Public Const AttackMine = 163 'removed since these should be built as vehicles themselves
	'Public Const PressureTriggerMine = 164
	'Public Const CommandTriggerMine = 165
	'Public Const SmartTriggerMine = 166
	''Public Const ParachuteMine = 167 'removed and added as option for  Comand and Smart Trigger mines
	'Public Const UnGuidedMissile = 168
	'Public Const UnGuidedTorpedo = 169
	'Public Const GuidedMissile = 170
	'Public Const GuidedTorpedo = 171
	'Public Const RainbowLaser = 172
	'Public Const BlueGreenLaser = 173
	'Public Const FlameThrower = 174
	'Public Const WaterCannon = 175
	'
	'' Propulsion
	'Public Const WheeledDrivetrain = 201
	'Public Const AllWheelDriveWheeledDrivetrain = 254
	'Public Const TrackedDrivetrain = 202
	'Public Const LegDrivetrain = 203
	'Public Const FlexibodyDrivetrain = 204
	'Public Const TTRRotorDrivetrain = 205
	'Public Const MMRRotorDrivetrain = 206
	'Public Const CARRotorDrivetrain = 207
	'Public Const OrnithopterDrivetrain = 208
	'Public Const AerialPropeller = 209
	'Public Const DuctedFan = 210
	'Public Const PaddleWheel = 211
	'Public Const ScrewPropeller = 212
	'Public Const lightScrewPropeller = 213
	'Public Const DuctedPropeller = 214
	'Public Const Hydrojet = 215
	'Public Const MHDTunnel = 216
	'Public Const RopeHarness = 217
	'Public Const YokeandPoleHarness = 218
	'Public Const ShaftandCollarHarness = 219
	'Public Const WhiffletreeHarness = 220
	'Public Const RowingPositions = 221
	'Public Const SquareRig = 222
	'Public Const ForeandAftRig = 255
	'Public Const FullRig = 256
	'Public Const AerialSail = 223
	'Public Const lightSail = 224
	'Public Const MagLevLifter = 225
	'Public Const Turbojet = 226
	'Public Const Turbofan = 227
	'Public Const Ramjet = 228
	'Public Const TurboRamjet = 229
	'Public Const Hyperfan = 230
	'Public Const FusionAirRam = 231
	'Public Const StandardThruster = 232
	'Public Const SuperThruster = 233
	'Public Const MegaThruster = 234
	'Public Const LiquidFuelRocket = 235
	'Public Const MOXRocket = 236
	'Public Const IonDrive = 237
	'Public Const FissionRocket = 238
	'Public Const FusionRocket = 239
	'Public Const OptimizedFusion = 240
	'Public Const AntimatterThermal = 241
	'Public Const AntimatterPion = 242
	'Public Const OrionEngine = 243
	'Public Const SolidRocketEngine = 244
	'Public Const Hyperdrive = 245
	'Public Const JumpDrive = 246
	'Public Const WarpDrive = 247
	'Public Const TeleportationDrive = 248
	'Public Const SubQuantumConveyor = 249
	'Public Const ContraGravGenerator = 250
	'Public Const HotAir = 251
	'Public Const Hydrogen = 252
	'Public Const Helium = 253
	'Public Const ThrustBomb = 257
	'Public Const QuantumConveyor = 258
	'Public Const TwoQuantumConveyor = 259
	'Public Const AerialSailForeAftRig = 260
	'
	'Public Const SimpleCustom = 1000
	'Public Const GroupComponent = 1100
	'
	'Public Const PerformanceProfile = 999
End Module