Attribute VB_Name = "modConstants"
'=====================================================
' Constant declaration for all vehicle objects
'=====================================================
' Subassemblies
Public Const CLASSNAME_PROPERTY_ITEM = "Vehicles.cPropertyItem"
Public Const CLASSNAME_VEHICLE = "Vehicles.cVehicle"
Public Const CLASSNAME_GROUP = "Vehicles.cGroup"
Public Const CLASSNAME_SURFACE = "Vehicles.cSurface"
Public Const CLASSNAME_FEATURE = "Vehicles.cFeature"
Public Const CLASSNAME_OPTIONS = "Vehicles.cOptions"
Public Const CLASSNAME_STATS = "Vehicles.cStats"
Public Const CLASSNAME_DESCRIPTION = "Vehicles.cDescription"
Public Const CLASSNAME_CREW = "Vehicles.cCrew"
Public Const CLASSNAME_AUTHOR = "Vehicles.cAuthor"

Public Const CLASSNAME_BODY = "Vehicles.aBody"
Public Const CLASSNAME_HAMMOCK = "Vehicles.aTest"

'=====================================================
' Interface ID's <-- cant be more than 32 (umm...  cuz of 32bitflag... but we'll see if this  holds up)
'=====================================================
Public Const INTERFACE_NODE = 0  ' some of these ID's are purely abstract.
Public Const INTERFACE_PERSIST = 1
Public Const INTERFACE_DISPLAY = 2
Public Const INTERFACE_BUILD = 12

Public Const INTERFACE_COMPONENT = 4 ' this type is more of a classID and less of a interface
Public Const INTERFACE_CONTAINER = 5
Public Const INTERFACE_SURFACE = 6
Public Const INTERFACE_FEATURE = 11
Public Const INTERFACE_VEHICLE = 7
Public Const INTERFACE_VEHICLE_DESCRIPTION = 8
Public Const INTERFACE_VEHICLE_VERSION = 9
Public Const INTERFACE_VEHICLE_AUTHOR = 10

Public Const INTERFACE_ARMOR = 30
Public Const INTERFACE_ARMOR_FACE = 31
Public Const INTERFACE_ARMOR_LAYER = 32

'=====================================================
' Node Attribute Constants
'=====================================================
' there are 2^6 combinations so we should write a util (later to be merged into comp editor) that
' will allow us to pick the attributes and it will produce the number we need to store in the XML def file
Public Const NODE_REQUIRED = 1&  '(e.g. no user delete)
Public Const NODE_FIXED = 2&      '(moveable within tree)
Public Const NODE_VISIBLE = 4&    '
Public Const NODE_RENAMEABLE = 8& '
Public Const NODE_COPYABLE = 16&  ' (node or branch - with a group, you shouldnt be able to save the group without any children though)
Public Const NODE_SAVEABLE = 32&  '
'Public Const NODE_PASTEABLE = 64& (actually if Copy is allowed, then goes to follow this would be allowed to IF the branch could accept children)

'=====================================================
' String Constants for drop down selections for various settings
' Note: The constants must match precisely with the order of the drop down list items
'       in the proplist items (which are loaded from the XML defs)
'=====================================================
Public Enum EMISSION_CLOAKING
    None = 0
    BASIC = 1
    RADICAL = 2
End Enum
    


Public Const Body = 1
Public Const Skid = 2
Public Const Wheel = 3
Public Const Track = 4
Public Const Leg = 5
Public Const Wing = 6
Public Const TTRotor = 7
Public Const Hydrofoil = 8
Public Const Hovercraft = 9
Public Const Superstructure = 10
Public Const OpenMount = 11
Public Const Mast = 12
Public Const Pod = 13
Public Const Turret = 14
Public Const Popturret = 15
Public Const Gasbag = 16
Public Const Arm = 17

' Other Pseudo Subs
'Public Const Armor = 18
Public Const Cargo = 23
Public Const equipmentPod = 27
Public Const SolarPanel = 28
Public Const SideCar = 29
Public Const ArmorOverall = 30
Public Const ArmorLocation = 31
Public Const ArmorBasicFacing = 32
Public Const ArmorComplexFacing = 33
Public Const ArmorGunShield = 34
Public Const ArmorWheelGuard = 35
Public Const ArmorOpenFrame = 36
Public Const SolarCellArray = 37
Public Const AutogyroRotor = 38
Public Const MMRotor = 39
Public Const CARotor = 40
Public Const ArmorComponent = 41


'Weapons and Weapon Accessories
'Public Const ArtilleryandGun = 101
'Public Const BeamWeapon = 102
'Public Const Launcher = 103
'Public Const TorpedoandMissile = 104
Public Const WeaponLink = 105
Public Const PartialStabilizationGear = 106
Public Const FullStabilizationGear = 111
Public Const UniversalMount = 107
Public Const CasemateMount = 112
Public Const DoorMount = 113
Public Const Cyberslave = 114
Public Const WeaponBay = 108
Public Const AntiBlastMagazine = 109
Public Const HardPoint = 110
Public Const Ammunition = 115
Public Const BoltThrower = 116
Public Const StoneThrower = 117
Public Const RepeatingBoltThrower = 118
Public Const MuzzleLoader = 119
Public Const BreechLoader = 120
Public Const ManualRepeater = 121
Public Const Revolver = 122
Public Const MechanicalGatling = 123
Public Const SlowAutoloader = 124
Public Const FastAutoloader = 125
Public Const lightAutomatic = 126
Public Const HeavyAutomatic = 127
Public Const ElectricGatling = 128


Public Const Laser = 129
Public Const UVLaser = 130
Public Const IRLaser = 131
Public Const Disruptor = 132
Public Const ChargedParticleBeam = 133
Public Const NeutralParticleBeam = 134
Public Const Flamer = 135
Public Const Screamer = 136
Public Const Stunner = 137
Public Const ParalysisBeam = 138
Public Const XRayLaser = 139
Public Const FusionBeam = 140
Public Const GravityBeam = 141
Public Const AntiparticleBeam = 142
Public Const Graser = 143
Public Const Disintegrator = 144
Public Const Displacer = 145
Public Const BeamedPowerTransmitter = 146
Public Const MilitaryParalysisBeam = 147
'Public Const EnergyDrill = 624 'is already listed above in Heavy Equipt.
Public Const DisposableLauncher = 148
Public Const MuzzleloadingLauncher = 149
Public Const BreechloadingLauncher = 150
Public Const ManualRepeaterLauncher = 151
Public Const SlowAutoLoaderLauncher = 152
Public Const FastAutoLoaderLauncher = 153
Public Const RevolverLauncher = 154
Public Const lightAutomaticLauncher = 155
Public Const HeavyAutomaticLauncher = 156

Public Const IronBomb = 157
Public Const RetardedBomb = 158
Public Const SmartBomb = 159
Public Const SelfDestructSystem = 160
Public Const ContactMine = 161
Public Const ProximityMine = 162
'Public Const AttackMine = 163 'removed since these should be built as vehicles themselves
Public Const PressureTriggerMine = 164
Public Const CommandTriggerMine = 165
Public Const SmartTriggerMine = 166
'Public Const ParachuteMine = 167 'removed and added as option for  Comand and Smart Trigger mines
Public Const UnGuidedMissile = 168
Public Const UnGuidedTorpedo = 169
Public Const GuidedMissile = 170
Public Const GuidedTorpedo = 171
Public Const RainbowLaser = 172
Public Const BlueGreenLaser = 173
Public Const FlameThrower = 174
Public Const WaterCannon = 175

' Propulsion
Public Const WheeledDrivetrain = 201
Public Const AllWheelDriveWheeledDrivetrain = 254
Public Const TrackedDrivetrain = 202
Public Const LegDrivetrain = 203
Public Const FlexibodyDrivetrain = 204
Public Const TTRRotorDrivetrain = 205
Public Const MMRRotorDrivetrain = 206
Public Const CARRotorDrivetrain = 207
Public Const OrnithopterDrivetrain = 208
Public Const AerialPropeller = 209
Public Const DuctedFan = 210
Public Const PaddleWheel = 211
Public Const ScrewPropeller = 212
Public Const lightScrewPropeller = 213
Public Const DuctedPropeller = 214
Public Const Hydrojet = 215
Public Const MHDTunnel = 216
Public Const RopeHarness = 217
Public Const YokeandPoleHarness = 218
Public Const ShaftandCollarHarness = 219
Public Const WhiffletreeHarness = 220
Public Const RowingPositions = 221
Public Const SquareRig = 222
Public Const ForeandAftRig = 255
Public Const FullRig = 256
Public Const AerialSail = 223
Public Const lightSail = 224
Public Const MagLevLifter = 225
Public Const Turbojet = 226
Public Const Turbofan = 227
Public Const Ramjet = 228
Public Const TurboRamjet = 229
Public Const Hyperfan = 230
Public Const FusionAirRam = 231
Public Const StandardThruster = 232
Public Const SuperThruster = 233
Public Const MegaThruster = 234
Public Const LiquidFuelRocket = 235
Public Const MOXRocket = 236
Public Const IonDrive = 237
Public Const FissionRocket = 238
Public Const FusionRocket = 239
Public Const OptimizedFusion = 240
Public Const AntimatterThermal = 241
Public Const AntimatterPion = 242
Public Const OrionEngine = 243
Public Const SolidRocketEngine = 244
Public Const Hyperdrive = 245
Public Const JumpDrive = 246
Public Const WarpDrive = 247
Public Const TeleportationDrive = 248
Public Const SubQuantumConveyor = 249
Public Const ContraGravGenerator = 250
Public Const HotAir = 251
Public Const Hydrogen = 252
Public Const Helium = 253
Public Const ThrustBomb = 257
Public Const QuantumConveyor = 258
Public Const TwoQuantumConveyor = 259
Public Const AerialSailForeAftRig = 260

'Manned Vehicle Components
Public Const PrimitiveManeuverControl = 301
Public Const MechanicalManeuverControl = 302
Public Const ElectronicManeuverControl = 303
Public Const ComputerizedManeuverControl = 304
'Public Const DuplicateMechanicalControl = 305
'Public Const DuplicateElectronicControl = 306
'Public Const DuplicateComputerizedControl = 307
Public Const MechanicalDivingControl = 308
'Public Const DuplicateDivingControl = 309
Public Const CrampedCrewStation = 310 '
Public Const NormalCrewStation = 311
Public Const RoomyCrewStation = 312
'Public Const ExposedCrewStation = 313 'this is just a user option
Public Const CycleCrewStation = 314
Public Const HarnessCrewStation = 315
Public Const BattlesuitSystem = 316
Public Const FormFittingBattleSuitSystem = 323
Public Const CrampedSeat = 317
Public Const NormalSeat = 318
Public Const RoomySeat = 319
Public Const CrampedStandingRoom = 320
Public Const NormalStandingRoom = 321
Public Const RoomyStandingRoom = 322
'Public Const ExposedSeat = 323 'these are just options
'Public Const ExposedStandingRoom = 324 'these are just options
Public Const CycleSeat = 325
Public Const Hammock = 326
Public Const Bunk = 327
Public Const Cabin = 328
Public Const LuxuryCabin = 329
Public Const EnvironmentalControl = 330
Public Const NBCKit = 331
Public Const LimitedLifeSystem = 332
Public Const FullLifeSystem = 333
Public Const Provisions = 334
Public Const ArtificialGravityUnit = 335
Public Const EjectionSeat = 336
Public Const CrewEscapeCapsule = 337
Public Const Airbag = 338
Public Const CrashWeb = 339
' Public Const GSeat = 340 ' This is a property of Seats and CrewStations
Public Const WombTank = 341
Public Const GravityWeb = 342
Public Const GravCompensator = 343
'Public Const BridgeAccessSpace = 344 'is now property of CrewStations
Public Const SmallGalley = 345
Public Const ElectronicDivingControl = 346
Public Const ComputerizedDivingControl = 347
Public Const TotalLifeSystem = 348
Public Const Suite = 349
Public Const LuxurySuite = 350
'Power and Fuel
Public Const MuscleEngine = 401
Public Const EarlySteamEngine = 402
Public Const ForcedDraftSteamEngine = 403
Public Const TripleExpansionSteamEngine = 404
Public Const SteamTurbine = 405
Public Const GasolineEngine = 406
Public Const HPGasolineEngine = 407
Public Const TurboGasolineEngine = 408
Public Const SuperGasolineEngine = 409
Public Const TurboHPGasolineEngine = 410
Public Const SuperHPGasolineEngine = 411
Public Const StandardDieselEngine = 412
Public Const TurboStandardDieselEngine = 413
Public Const MarineDieselEngine = 414
Public Const HPDieselEngine = 416
Public Const TurboHPDieselEngine = 417
Public Const NitrousOxideBooster = 418
Public Const Snorkel = 419
Public Const StandardGasTurbine = 420
Public Const HPGasTurbine = 421
Public Const OptimizedGasTurbine = 422
Public Const StandardMHDTurbine = 423
Public Const HPMHDTurbine = 424
Public Const FuelCell = 425
Public Const FissionReactor = 426
Public Const RTGReactor = 427
Public Const NPU = 428
Public Const FusionReactor = 429
Public Const AntimatterReactor = 430
Public Const TotalConversionPowerPlant = 431
Public Const CosmicPowerPlant = 432
Public Const Soulburner = 433
Public Const ElementalFurnace = 435
Public Const ManaEngine = 436
Public Const Carnivore = 437
Public Const Herbivore = 438
Public Const Omnivore = 439
Public Const Vampire = 440
Public Const ElectricContactPower = 441
Public Const LaserBeamedPowerReceiver = 442
Public Const MaserBeamedPowerReceiver = 443
Public Const ClockWork = 444
Public Const LeadAcidBattery = 445
Public Const AdvancedBattery = 446
Public Const Flywheel = 447
Public Const RechargeablePowerCell = 448
Public Const PowerCell = 449
Public Const CoalBunker = 450
Public Const WoodBunker = 451
Public Const StandardTank = 452
Public Const lightTank = 453
Public Const UltralightTank = 454
Public Const StandardSelfSealingTank = 455
Public Const lightSelfSealingTank = 456
Public Const UltralightSelfSealingTank = 457
Public Const Water = 458
Public Const Gasoline = 459
Public Const Diesel = 460
Public Const AviationGas = 461
Public Const JetFuel = 462
Public Const Propane = 463
Public Const LiquifiedNaturalGas = 464
Public Const EthanolAlchohol = 465
Public Const MethanolAlchohol = 466
Public Const LiquidHydrogen = 467
Public Const LiquidOxygen = 468
Public Const Cadmium = 469
Public Const MetalLOX = 470
Public Const RocketFuel = 471
Public Const AntiMatter = 472
Public Const AntiMatterBay = 473
Public Const CeramicEngine = 474
Public Const TurboCeramicEngine = 475
Public Const SuperCeramicEngine = 476
Public Const HPCeramicEngine = 477
Public Const TurboHPCeramicEngine = 478
Public Const SuperHPCeramicEngine = 479
Public Const HydrogenCombustionEngine = 480
Public Const Wood = 481
Public Const Coal = 482
Public Const UraniumFuelRod = 483


'Instruments and Electronics
Public Const RadioCommunicator = 5001
Public Const TightBeamRadio = 5002
Public Const VLFRadio = 5003
Public Const CellularPhone = 5004
Public Const CellularPhonewithRadio = 5005
Public Const RadioJammer = 5006
Public Const ElfReceiver = 5007
Public Const LaserCommunicator = 5008
Public Const NeutrinoCommunicator = 5009
Public Const GravityRippleCommunicator = 5010
Public Const Headlight = 5011
Public Const Searchlight = 5012
Public Const InfraredSearchlight = 5013
Public Const Telescope = 5014
Public Const lightAmplification = 5015
Public Const LowlightTV = 5016
Public Const ExtendableSensorPeriscope = 5017
Public Const Radar = 5018
Public Const Ladar = 5019
Public Const ActiveSonar = 5020
Public Const PassiveSonar = 5021
Public Const PassiveInfrared = 5022
Public Const Thermograph = 5023
Public Const PassiveRadar = 5024
Public Const PESA = 5025
Public Const Geophone = 5026
Public Const MAD = 5027
Public Const MultiScanner = 5028
Public Const ChemScanner = 5029
Public Const RadScanner = 5030
Public Const BioScanner = 5031
Public Const GravScanner = 5032
Public Const RangingSoundDetector = 5033
Public Const MeteorologicalInstruments = 5034
'Public Const AstronomicalTelescope = 5035 'user now builds these like normal telescopes and adds stabilization
Public Const AstronomicalInstruments = 5036
Public Const LowResPlanetarySurveyArray = 5037
Public Const MedResPlanetarySurveyArray = 5038
Public Const HighResPlanetarySurveyArray = 5039
Public Const SoundSystem = 5040
Public Const FlightRecorder = 5041
Public Const VehicleCamera = 5042
Public Const DigitalVehicleCamera = 5043
Public Const ReconCamera = 5044
Public Const DigitalReconCamera = 5045
'Public Const InfraredCamera = 5046 'these are now hardcoded and not read from table
'Public Const LowlightCamera = 5047  'these are now hardcoded and not read from table
Public Const NavigationInstruments = 5048
'Public Const PrecisionNavigationInstruments = 5049 'hardcoded option
Public Const NavigationalRadar = 5050
Public Const AntiCollisionRadar = 5051
Public Const AutoPilot = 5052
Public Const IFF = 5053
Public Const Transponder = 5054
Public Const INS = 5055
Public Const GPS = 5056
Public Const MilitaryGPS = 5057
Public Const TFR = 5058
Public Const OpticalBombSight = 5059
Public Const FireDirectionCenter = 5060
Public Const HUDWAC = 5061
Public Const PupilHUDWAC = 5062
Public Const LaserRangeFinder = 5063
Public Const LaserDesignator = 5064
Public Const LaserSpotTracker = 5065
Public Const RadarDetector = 5066
'Public Const AdvancedRadarDetector = 5067 'hardcoded option
Public Const LaserSensor = 5068
Public Const LaserRadarDetector = 5069
'Public Const AdvancedLaserRadarDetector = 5070 'hardcoded option
Public Const RadioDirectionFinder = 5071
Public Const AreaRadarJammer = 5072
Public Const DeceptiveRadarJammer = 5073
Public Const InfraredJammer = 5074
Public Const ChaffDecoyDischarger = 5075
Public Const RadarReflector = 5076
Public Const BlipEnhancer = 5077
Public Const TEMPEST = 5078
Public Const MacroFrame = 5079
Public Const MainFrame = 5080
Public Const MicroFrame = 5081
Public Const MiniComputer = 5082
Public Const SmallComputer = 5083
Public Const Terminal = 5084
Public Const FireDirectionSoftware = 5085
Public Const DatabaseSoftware = 5086
Public Const CartographySoftware = 5087
Public Const ComputerNavigationSoftware = 5088
Public Const DatalinkSoftware = 5089
Public Const TargetingSoftware = 5090
Public Const TransmissionProfilingSoftware = 5091
Public Const GunnerSoftware = 5092
Public Const DamageControlSoftware = 5093
Public Const PersonalitySimulationSoftwareFull = 5094
Public Const RobotSkillProgramsPhysical = 5095
Public Const RoutineVehicleOperationSoftwarePilot = 5096
Public Const SurgicalInterface = 5097
Public Const InterfaceWeb = 5098
Public Const AutoInterfaceWeb = 5099
Public Const SocketInterface = 5100
Public Const NeuralInductionField = 5101
Public Const ImprovedOpticalBombSight = 5102
Public Const AdvancedOpticalBombSight = 5103
Public Const PersonalitySimulationLimited = 5104
Public Const RoutineVehicleOperationSoftwareOther = 5105
Public Const SurveillanceSoundDetector = 5106
Public Const RobotSkillProgramsMental = 5107
Public Const HoloventureProgram = 5108
Public Const LowResImagingRadar = 5109
Public Const HiResImagingRadar = 5110
Public Const AESA = 5111
Public Const DecoyChaff = 5112
Public Const DecoySmoke = 5113
Public Const DecoyFlares = 5114
Public Const DecoySonarDecoy = 5115
Public Const DecoyHotSmoke = 5116
Public Const DecoyPrism = 5117
Public Const DecoyBlackOutGas = 5118
Public Const SmokeDecoyDischarger = 5119
Public Const FlareDecoyDischarger = 5120
Public Const SonarDecoyDischarger = 5121
Public Const HotSmokeDecoyDischarger = 5122
Public Const PrismDecoyDischarger = 5123
Public Const BlackOutGasDecoyDischarger = 5124
Public Const DeflectorField = 5125
Public Const ForceScreen = 5126
Public Const VariableForceScreen = 5127

'Miscellaneous equipment
Public Const ArmMotor = 601
Public Const FireExtinguisherSystem = 602
Public Const FullFireSuppressionSystem = 603
Public Const CompactFireSuppressionSystem = 604
Public Const BilgePump = 605
Public Const CompleteWorkshop = 606
Public Const MechanicWorkshop = 607
Public Const EngineeringWorkshop = 608
Public Const ElectronicsWorkshop = 609
Public Const ArmouryWorkshop = 610
Public Const CompleteMiniWorkshop = 611
Public Const ScienceLab = 612  'LOOKUP SKILLS IN BASIC SET 59-62
Public Const ExtendableLadder = 613
Public Const Crane = 614
Public Const Winch = 615
Public Const PowerShovel = 616
Public Const WreckingCrane = 617
Public Const ForkLift = 618
Public Const VehicularBridge = 619
Public Const LaunchCatapult = 620
Public Const SkyHook = 621
Public Const Bore = 622
Public Const SuperBore = 623
Public Const EnergyDrill = 624
Public Const TractorBeam = 625
Public Const PressorBeam = 626
Public Const OperatingRoom = 627
Public Const StretcherPallet = 628
Public Const EmergencySupportUnit = 629
Public Const EmergencylightsandSiren = 630
Public Const CryonicCapsule = 631
Public Const Automed = 632
Public Const DiagnosisTable = 633
Public Const Stage = 634
Public Const Hall = 635
Public Const BarRoom = 636
Public Const ConferenceRoom = 637
'Public Const SwimmingPool = 638 'user must build this themselves
Public Const MovieScreenandProjector = 639
Public Const MovieScreenandProjectorSmall = 640
Public Const HoloventureZone = 641
'Public Const NeuralInterfaceEntertainment = 642
'Public Const Door = 643
'Public Const Hatch = 644
Public Const CargoRamp = 645
Public Const Airlock = 646
Public Const MembraneAirlock = 647
Public Const Forcelock = 648
Public Const PassageTube = 649
Public Const TeleportProjector = 650
Public Const BrigsandRestraints = 651
Public Const BurglarAlarm = 652
Public Const HighSecurityAlarm = 653
Public Const MutableLicensePlate = 655
Public Const OilSprayer = 656
Public Const PaintSprayer = 657
Public Const SmokeScreen = 659
Public Const SpikeDropper = 660
Public Const VehicleBay = 661
Public Const HangerBay = 662
Public Const DryDock = 663
Public Const SpaceDock = 664
Public Const ExternalCradle = 665
Public Const ArrestorHook = 666
Public Const VehicularParachute = 667
Public Const RefuellingProbe = 668
Public Const RefuellingDrogue = 669
Public Const FuelElectrolysisSystem = 670
Public Const HydrogenFuelScoop = 671
Public Const AtmosphereProcessor = 672
Public Const NuclearDamper = 673
Public Const SmallRealityStabilizer = 674
Public Const ModularSocket = 675
Public Const Module = 676
Public Const MiniMechanicWorkshop = 677
Public Const CombinationBeam = 678
Public Const ArmoredPassageTube = 679
Public Const MediumRealityStabilizer = 680
Public Const HeavyRealityStabilizer = 681
Public Const CraneWithElectroMagnet = 682
Public Const MiniElectronicsWorkshop = 683
Public Const MiniEngineeringWorkshop = 684
Public Const MiniArmouryWorkshop = 685

' PERFORMANCE PROFILES
Public Const PERFORMANCEPROFILE = 999
Public Const PERFORMANCEAIR = 980
Public Const PERFORMANCEHOVER = 981
Public Const PERFORMANCEMAGLEV = 982
Public Const PERFORMANCEWATER = 983
Public Const PERFORMANCESUB = 984
Public Const PERFORMANCELEG = 985
Public Const PERFORMANCETRACK = 986
Public Const PERFORMANCEWHEEL = 987
Public Const PERFORMANCEFLEX = 988
Public Const PERFORMANCESKID = 989
Public Const PERFORMANCESPACE = 990

' CUSTOM AND CONTAINERS
Public Const SimpleCustom = 1000
Public Const GroupComponent = 1100

' Key Constants for some special tree node types (uses 1200 series data type values)
Public Const VEHICLE_NODE = 1200          'linked to clsStats
'Public Const SETTINGS_NODE = 1201         'linked to clsSettings
'Public Const SURFACE_NODE = 1202          'linked to clsSurface
'Public Const OPTIONS_NODE = 1203          'linked to clsOptions - Stats only since these options like swept wings and snow tires are set elsewhere
                                           ' also stuff like cargo weight, access space mods etc
'Public Const DESCRIPTION_NODE = 1204      ' linked to clsDescription
Public Const CREW_NODE = 1205
    
Public Const PERFORMANCE_NODE = 1206     ' linked to  NOTHING?
Public Const POWERSYSTEMS_NODE = 1207    ' linked to NOTHING?
Public Const WEAPON_LINKS_NODE = 1208    ' linked to NOTHING?
Public Const FUELSYSTEMS_NODE = 1209     ' linked to NOTHING?


Public Const BODY_KEY = "1_"            ' linked to clsBody

' Reserved Keys for Battlesuits
Public Const BATTLESUIT_KEY_SYSTEM = "2_"
Public Const BATTLESUIT_KEY_HEAD = "3_"
Public Const BATTLESUIT_KEY_LEFT_ARM = "4_"
Public Const BATTLESUIT_KEY_LEFT_ARM_MOTOR = "5_"
Public Const BATTLESUIT_KEY_RIGHT_ARM = "6_"
Public Const BATTLESUIT_KEY_RIGHT_ARM_MOTOR = "7_"
Public Const BATTLESUIT_KEY_LEFT_LEG = "8_"
Public Const BATTLESUIT_KEY_LEFT_LEG_MOTOR = "9_"
Public Const BATTLESUIT_KEY_RIGHT_LEG = "10_"
Public Const BATTLESUIT_KEY_RIGHT_LEG_MOTOR = "11_"

' Reserved Keys for Default Nodes
'Public Const VEHICLE_KEY = "0_"          'linked to clsStats
'Public Const SETTINGS_KEY = "12_"         'linked to clsSettings
'Public Const SURFACE_KEY = "13_"          'linked to clsSurface
'Public Const OPTIONS_KEY = "14_"          'linked to clsOptions - Stats only since these options like swept wings and snow tires are set elsewhere
                                           ' also stuff like cargo weight, access space mods etc
Public Const DESCRIPTION_KEY = "DKEY"      ' linked to clsDescription
Public Const CREW_KEY = "CKEY"
    
Public Const PERFORMANCE_KEY = "PKEY"     ' linked to  NOTHING?
Public Const POWERSYSTEMS_KEY = "PWKEY"    ' linked to NOTHING?
Public Const WEAPON_LINKS_KEY = "WLKEY"    ' linked to NOTHING?
Public Const FUELSYSTEMS_KEY = "FKEY"     ' linked to NOTHING?

Public Const GROUP_NAME = "Group"
Public Const CHILD_GROUP_NAME = "Child Group"


' Constants for Checklist and TreeX view modes
Public Const FUEL_PROFILE = 1
Public Const POWER_PROFILE = 2
Public Const WEAPON_CHECKLIST = 1
Public Const PERFORMANCE_CHECKLIST = 2

''=====================================================
'' Constant declaration for all vehicle objects
''=====================================================
'' Subassemblies
'Public Const Body = 1
'Public Const Skid = 2
'Public Const Wheel = 3
'Public Const Track = 4
'Public Const Leg = 5
'Public Const Wing = 6
'Public Const TTRotor = 7
'Public Const Hydrofoil = 8
'Public Const Hovercraft = 9
'Public Const Superstructure = 10
'Public Const OpenMount = 11
'Public Const Mast = 12
'Public Const Pod = 13
'Public Const Turret = 14
'Public Const Popturret = 15
'Public Const Gasbag = 16
'Public Const Arm = 17
'' Other Pseudo Subs
''Public Const Armor = 18
'Public Const Cargo = 23
'Public Const equipmentPod = 27
'Public Const SolarPanel = 28
'Public Const SideCar = 29
'Public Const ArmorOverall = 30
'Public Const ArmorLocation = 31
'Public Const ArmorBasicFacing = 32
'Public Const ArmorComplexFacing = 33
'Public Const ArmorGunShield = 34
'Public Const ArmorWheelGuard = 35
'Public Const ArmorOpenFrame = 36
'Public Const SolarCellArray = 37
'Public Const AutogyroRotor = 38
'Public Const MMRotor = 39
'Public Const CARotor = 40
'Public Const ArmorComponent = 41
'
''Instruments and Electronics
'Public Const RadioCommunicator = 5001
'Public Const TightBeamRadio = 5002
'Public Const VLFRadio = 5003
'Public Const CellularPhone = 5004
'Public Const CellularPhonewithRadio = 5005
'Public Const RadioJammer = 5006
'Public Const ElfReceiver = 5007
'Public Const LaserCommunicator = 5008
'Public Const NeutrinoCommunicator = 5009
'Public Const GravityRippleCommunicator = 5010
'Public Const Headlight = 5011
'Public Const Searchlight = 5012
'Public Const InfraredSearchlight = 5013
'Public Const Telescope = 5014
'Public Const lightAmplification = 5015
'Public Const LowlightTV = 5016
'Public Const ExtendableSensorPeriscope = 5017
'Public Const Radar = 5018
'Public Const Ladar = 5019
'Public Const ActiveSonar = 5020
'Public Const PassiveSonar = 5021
'Public Const PassiveInfrared = 5022
'Public Const Thermograph = 5023
'Public Const PassiveRadar = 5024
'Public Const PESA = 5025
'Public Const Geophone = 5026
'Public Const MAD = 5027
'Public Const MultiScanner = 5028
'Public Const ChemScanner = 5029
'Public Const RadScanner = 5030
'Public Const BioScanner = 5031
'Public Const GravScanner = 5032
'Public Const RangingSoundDetector = 5033
'Public Const MeteorologicalInstruments = 5034
''Public Const AstronomicalTelescope = 5035 'user now builds these like normal telescopes and adds stabilization
'Public Const AstronomicalInstruments = 5036
'Public Const LowResPlanetarySurveyArray = 5037
'Public Const MedResPlanetarySurveyArray = 5038
'Public Const HighResPlanetarySurveyArray = 5039
'Public Const SoundSystem = 5040
'Public Const FlightRecorder = 5041
'Public Const VehicleCamera = 5042
'Public Const DigitalVehicleCamera = 5043
'Public Const ReconCamera = 5044
'Public Const DigitalReconCamera = 5045
''Public Const InfraredCamera = 5046 'these are now hardcoded and not read from table
''Public Const LowlightCamera = 5047  'these are now hardcoded and not read from table
'Public Const NavigationInstruments = 5048
''Public Const PrecisionNavigationInstruments = 5049 'hardcoded option
'Public Const NavigationalRadar = 5050
'Public Const AntiCollisionRadar = 5051
'Public Const AutoPilot = 5052
'Public Const IFF = 5053
'Public Const Transponder = 5054
'Public Const INS = 5055
'Public Const GPS = 5056
'Public Const MilitaryGPS = 5057
'Public Const TFR = 5058
'Public Const OpticalBombSight = 5059
'Public Const FireDirectionCenter = 5060
'Public Const HUDWAC = 5061
'Public Const PupilHUDWAC = 5062
'Public Const LaserRangeFinder = 5063
'Public Const LaserDesignator = 5064
'Public Const LaserSpotTracker = 5065
'Public Const RadarDetector = 5066
''Public Const AdvancedRadarDetector = 5067 'hardcoded option
'Public Const LaserSensor = 5068
'Public Const LaserRadarDetector = 5069
''Public Const AdvancedLaserRadarDetector = 5070 'hardcoded option
'Public Const RadioDirectionFinder = 5071
'Public Const AreaRadarJammer = 5072
'Public Const DeceptiveRadarJammer = 5073
'Public Const InfraredJammer = 5074
'Public Const ChaffDecoyDischarger = 5075
'Public Const RadarReflector = 5076
'Public Const BlipEnhancer = 5077
'Public Const TEMPEST = 5078
'Public Const MacroFrame = 5079
'Public Const MainFrame = 5080
'Public Const MicroFrame = 5081
'Public Const MiniComputer = 5082
'Public Const SmallComputer = 5083
'Public Const Terminal = 5084
'Public Const FireDirectionSoftware = 5085
'Public Const DatabaseSoftware = 5086
'Public Const CartographySoftware = 5087
'Public Const ComputerNavigationSoftware = 5088
'Public Const DatalinkSoftware = 5089
'Public Const TargetingSoftware = 5090
'Public Const TransmissionProfilingSoftware = 5091
'Public Const GunnerSoftware = 5092
'Public Const DamageControlSoftware = 5093
'Public Const PersonalitySimulationSoftwareFull = 5094
'Public Const RobotSkillProgramsPhysical = 5095
'Public Const RoutineVehicleOperationSoftwarePilot = 5096
'Public Const SurgicalInterface = 5097
'Public Const InterfaceWeb = 5098
'Public Const AutoInterfaceWeb = 5099
'Public Const SocketInterface = 5100
'Public Const NeuralInductionField = 5101
'Public Const ImprovedOpticalBombSight = 5102
'Public Const AdvancedOpticalBombSight = 5103
'Public Const PersonalitySimulationLimited = 5104
'Public Const RoutineVehicleOperationSoftwareOther = 5105
'Public Const SurveillanceSoundDetector = 5106
'Public Const RobotSkillProgramsMental = 5107
'Public Const HoloventureProgram = 5108
'Public Const LowResImagingRadar = 5109
'Public Const HiResImagingRadar = 5110
'Public Const AESA = 5111
'Public Const DecoyChaff = 5112
'Public Const DecoySmoke = 5113
'Public Const DecoyFlares = 5114
'Public Const DecoySonarDecoy = 5115
'Public Const DecoyHotSmoke = 5116
'Public Const DecoyPrism = 5117
'Public Const DecoyBlackOutGas = 5118
'Public Const SmokeDecoyDischarger = 5119
'Public Const FlareDecoyDischarger = 5120
'Public Const SonarDecoyDischarger = 5121
'Public Const HotSmokeDecoyDischarger = 5122
'Public Const PrismDecoyDischarger = 5123
'Public Const BlackOutGasDecoyDischarger = 5124
'Public Const DeflectorField = 5125
'Public Const ForceScreen = 5126
'Public Const VariableForceScreen = 5127
'
''Miscellaneous equipment
'Public Const ArmMotor = 601
'Public Const FireExtinguisherSystem = 602
'Public Const FullFireSuppressionSystem = 603
'Public Const CompactFireSuppressionSystem = 604
'Public Const BilgePump = 605
'Public Const CompleteWorkshop = 606
'Public Const MechanicWorkshop = 607
'Public Const EngineeringWorkshop = 608
'Public Const ElectronicsWorkshop = 609
'Public Const ArmouryWorkshop = 610
'Public Const CompleteMiniWorkshop = 611
'Public Const ScienceLab = 612  'LOOKUP SKILLS IN BASIC SET 59-62
'Public Const ExtendableLadder = 613
'Public Const Crane = 614
'Public Const Winch = 615
'Public Const PowerShovel = 616
'Public Const WreckingCrane = 617
'Public Const ForkLift = 618
'Public Const VehicularBridge = 619
'Public Const LaunchCatapult = 620
'Public Const SkyHook = 621
'Public Const Bore = 622
'Public Const SuperBore = 623
'Public Const TractorBeam = 625
'Public Const PressorBeam = 626
'Public Const OperatingRoom = 627
'Public Const StretcherPallet = 628
'Public Const EmergencySupportUnit = 629
'Public Const EmergencylightsandSiren = 630
'Public Const CryonicCapsule = 631
'Public Const Automed = 632
'Public Const DiagnosisTable = 633
'Public Const Stage = 634
'Public Const Hall = 635
'Public Const BarRoom = 636
'Public Const ConferenceRoom = 637
''Public Const SwimmingPool = 638 'user must build this themselves
'Public Const MovieScreenandProjector = 639
'Public Const MovieScreenandProjectorSmall = 640
'Public Const HoloventureZone = 641
''Public Const NeuralInterfaceEntertainment = 642
''Public Const Door = 643
''Public Const Hatch = 644
'Public Const CargoRamp = 645
'Public Const Airlock = 646
'Public Const MembraneAirlock = 647
'Public Const Forcelock = 648
'Public Const PassageTube = 649
'Public Const TeleportProjector = 650
'Public Const BrigsandRestraints = 651
'Public Const BurglarAlarm = 652
'Public Const HighSecurityAlarm = 653
'Public Const MutableLicensePlate = 655
'Public Const OilSprayer = 656
'Public Const PaintSprayer = 657
'Public Const SmokeScreen = 659
'Public Const SpikeDropper = 660
'Public Const VehicleBay = 661
'Public Const HangerBay = 662
'Public Const DryDock = 663
'Public Const SpaceDock = 664
'Public Const ExternalCradle = 665
'Public Const ArrestorHook = 666
'Public Const VehicularParachute = 667
'Public Const RefuellingProbe = 668
'Public Const RefuellingDrogue = 669
'Public Const FuelElectrolysisSystem = 670
'Public Const HydrogenFuelScoop = 671
'Public Const AtmosphereProcessor = 672
'Public Const NuclearDamper = 673
'Public Const SmallRealityStabilizer = 674
'Public Const ModularSocket = 675
'Public Const Module = 676
'Public Const MiniMechanicWorkshop = 677
'Public Const CombinationBeam = 678
'Public Const ArmoredPassageTube = 679
'Public Const MediumRealityStabilizer = 680
'Public Const HeavyRealityStabilizer = 681
'Public Const CraneWithElectroMagnet = 682
'Public Const MiniElectronicsWorkshop = 683
'Public Const MiniEngineeringWorkshop = 684
'Public Const MiniArmouryWorkshop = 685
'
''Manned Vehicle Components
'Public Const PrimitiveManeuverControl = 301
'Public Const MechanicalManeuverControl = 302
'Public Const ElectronicManeuverControl = 303
'Public Const ComputerizedManeuverControl = 304
''Public Const DuplicateMechanicalControl = 305
''Public Const DuplicateElectronicControl = 306
''Public Const DuplicateComputerizedControl = 307
'Public Const MechanicalDivingControl = 308
''Public Const DuplicateDivingControl = 309
'Public Const CrampedCrewStation = 310 '
'Public Const NormalCrewStation = 311
'Public Const RoomyCrewStation = 312
''Public Const ExposedCrewStation = 313 'this is just a user option
'Public Const CycleCrewStation = 314
'Public Const HarnessCrewStation = 315
'Public Const BattlesuitSystem = 316
'Public Const FormFittingBattleSuitSystem = 323
'Public Const CrampedSeat = 317
'Public Const NormalSeat = 318
'Public Const RoomySeat = 319
'Public Const CrampedStandingRoom = 320
'Public Const NormalStandingRoom = 321
'Public Const RoomyStandingRoom = 322
''Public Const ExposedSeat = 323 'these are just options
''Public Const ExposedStandingRoom = 324 'these are just options
'Public Const CycleSeat = 325
'Public Const Hammock = 326
'Public Const Bunk = 327
'Public Const Cabin = 328
'Public Const LuxuryCabin = 329
'Public Const EnvironmentalControl = 330
'Public Const NBCKit = 331
'Public Const LimitedLifeSystem = 332
'Public Const FullLifeSystem = 333
'Public Const Provisions = 334
'Public Const ArtificialGravityUnit = 335
'Public Const EjectionSeat = 336
'Public Const CrewEscapeCapsule = 337
'Public Const Airbag = 338
'Public Const CrashWeb = 339
'' Public Const GSeat = 340 ' This is a property of Seats and CrewStations
'Public Const WombTank = 341
'Public Const GravityWeb = 342
'Public Const GravCompensator = 343
''Public Const BridgeAccessSpace = 344 'is now property of CrewStations
'Public Const SmallGalley = 345
'Public Const ElectronicDivingControl = 346
'Public Const ComputerizedDivingControl = 347
'Public Const TotalLifeSystem = 348
'Public Const Suite = 349
'Public Const LuxurySuite = 350
''Power and Fuel
'Public Const MuscleEngine = 401
'Public Const EarlySteamEngine = 402
'Public Const ForcedDraftSteamEngine = 403
'Public Const TripleExpansionSteamEngine = 404
'Public Const SteamTurbine = 405
'Public Const GasolineEngine = 406
'Public Const HPGasolineEngine = 407
'Public Const TurboGasolineEngine = 408
'Public Const SuperGasolineEngine = 409
'Public Const TurboHPGasolineEngine = 410
'Public Const SuperHPGasolineEngine = 411
'Public Const StandardDieselEngine = 412
'Public Const TurboStandardDieselEngine = 413
'Public Const MarineDieselEngine = 414
'Public Const HPDieselEngine = 416
'Public Const TurboHPDieselEngine = 417
'Public Const NitrousOxideBooster = 418
'Public Const Snorkel = 419
'Public Const StandardGasTurbine = 420
'Public Const HPGasTurbine = 421
'Public Const OptimizedGasTurbine = 422
'Public Const StandardMHDTurbine = 423
'Public Const HPMHDTurbine = 424
'Public Const FuelCell = 425
'Public Const FissionReactor = 426
'Public Const RTGReactor = 427
'Public Const NPU = 428
'Public Const FusionReactor = 429
'Public Const AntimatterReactor = 430
'Public Const TotalConversionPowerPlant = 431
'Public Const CosmicPowerPlant = 432
'Public Const Soulburner = 433
'Public Const ElementalFurnace = 435
'Public Const ManaEngine = 436
'Public Const Carnivore = 437
'Public Const Herbivore = 438
'Public Const Omnivore = 439
'Public Const Vampire = 440
'Public Const ElectricContactPower = 441
'Public Const LaserBeamedPowerReceiver = 442
'Public Const MaserBeamedPowerReceiver = 443
'Public Const ClockWork = 444
'Public Const LeadAcidBattery = 445
'Public Const AdvancedBattery = 446
'Public Const Flywheel = 447
'Public Const RechargeablePowerCell = 448
'Public Const PowerCell = 449
'Public Const CoalBunker = 450
'Public Const WoodBunker = 451
'Public Const StandardTank = 452
'Public Const lightTank = 453
'Public Const UltralightTank = 454
'Public Const StandardSelfSealingTank = 455
'Public Const lightSelfSealingTank = 456
'Public Const UltralightSelfSealingTank = 457
'Public Const Water = 458
'Public Const Gasoline = 459
'Public Const Diesel = 460
'Public Const AviationGas = 461
'Public Const JetFuel = 462
'Public Const Propane = 463
'Public Const LiquifiedNaturalGas = 464
'Public Const EthanolAlchohol = 465
'Public Const MethanolAlchohol = 466
'Public Const LiquidHydrogen = 467
'Public Const LiquidOxygen = 468
'Public Const Cadmium = 469
'Public Const MetalLOX = 470
'Public Const RocketFuel = 471
'Public Const AntiMatter = 472
'Public Const AntiMatterBay = 473
'Public Const CeramicEngine = 474
'Public Const TurboCeramicEngine = 475
'Public Const SuperCeramicEngine = 476
'Public Const HPCeramicEngine = 477
'Public Const TurboHPCeramicEngine = 478
'Public Const SuperHPCeramicEngine = 479
'Public Const HydrogenCombustionEngine = 480
'Public Const Wood = 481
'Public Const Coal = 482
'Public Const UraniumFuelRod = 483
''Weapons and Weapon Accessories
''Public Const ArtilleryandGun = 101
''Public Const BeamWeapon = 102
''Public Const Launcher = 103
''Public Const TorpedoandMissile = 104
'Public Const WeaponLink = 105
'Public Const PartialStabilizationGear = 106
'Public Const FullStabilizationGear = 111
'Public Const UniversalMount = 107
'Public Const CasemateMount = 112
'Public Const DoorMount = 113
'Public Const Cyberslave = 114
'Public Const WeaponBay = 108
'Public Const AntiBlastMagazine = 109
'Public Const HardPoint = 110
'Public Const Ammunition = 115
'Public Const BoltThrower = 116
'Public Const StoneThrower = 117
'Public Const RepeatingBoltThrower = 118
'Public Const MuzzleLoader = 119
'Public Const BreechLoader = 120
'Public Const ManualRepeater = 121
'Public Const Revolver = 122
'Public Const MechanicalGatling = 123
'Public Const SlowAutoloader = 124
'Public Const FastAutoloader = 125
'Public Const lightAutomatic = 126
'Public Const HeavyAutomatic = 127
'Public Const ElectricGatling = 128
'
'
'Public Const Laser = 129
'Public Const UVLaser = 130
'Public Const IRLaser = 131
'Public Const Disruptor = 132
'Public Const ChargedParticleBeam = 133
'Public Const NeutralParticleBeam = 134
'Public Const Flamer = 135
'Public Const Screamer = 136
'Public Const Stunner = 137
'Public Const ParalysisBeam = 138
'Public Const XRayLaser = 139
'Public Const FusionBeam = 140
'Public Const GravityBeam = 141
'Public Const AntiparticleBeam = 142
'Public Const Graser = 143
'Public Const Disintegrator = 144
'Public Const Displacer = 145
'Public Const BeamedPowerTransmitter = 146
'Public Const MilitaryParalysisBeam = 147
'Public Const DisposableLauncher = 148
'Public Const MuzzleloadingLauncher = 149
'Public Const BreechloadingLauncher = 150
'Public Const ManualRepeaterLauncher = 151
'Public Const SlowAutoLoaderLauncher = 152
'Public Const FastAutoLoaderLauncher = 153
'Public Const RevolverLauncher = 154
'Public Const lightAutomaticLauncher = 155
'Public Const HeavyAutomaticLauncher = 156
'
'Public Const IronBomb = 157
'Public Const RetardedBomb = 158
'Public Const SmartBomb = 159
'Public Const SelfDestructSystem = 160
'Public Const ContactMine = 161
'Public Const ProximityMine = 162
''Public Const AttackMine = 163 'removed since these should be built as vehicles themselves
'Public Const PressureTriggerMine = 164
'Public Const CommandTriggerMine = 165
'Public Const SmartTriggerMine = 166
''Public Const ParachuteMine = 167 'removed and added as option for  Comand and Smart Trigger mines
'Public Const UnGuidedMissile = 168
'Public Const UnGuidedTorpedo = 169
'Public Const GuidedMissile = 170
'Public Const GuidedTorpedo = 171
'Public Const RainbowLaser = 172
'Public Const BlueGreenLaser = 173
'Public Const FlameThrower = 174
'Public Const WaterCannon = 175
'
'' Propulsion
'Public Const WheeledDrivetrain = 201
'Public Const AllWheelDriveWheeledDrivetrain = 254
'Public Const TrackedDrivetrain = 202
'Public Const LegDrivetrain = 203
'Public Const FlexibodyDrivetrain = 204
'Public Const TTRRotorDrivetrain = 205
'Public Const MMRRotorDrivetrain = 206
'Public Const CARRotorDrivetrain = 207
'Public Const OrnithopterDrivetrain = 208
'Public Const AerialPropeller = 209
'Public Const DuctedFan = 210
'Public Const PaddleWheel = 211
'Public Const ScrewPropeller = 212
'Public Const lightScrewPropeller = 213
'Public Const DuctedPropeller = 214
'Public Const Hydrojet = 215
'Public Const MHDTunnel = 216
'Public Const RopeHarness = 217
'Public Const YokeandPoleHarness = 218
'Public Const ShaftandCollarHarness = 219
'Public Const WhiffletreeHarness = 220
'Public Const RowingPositions = 221
'Public Const SquareRig = 222
'Public Const ForeandAftRig = 255
'Public Const FullRig = 256
'Public Const AerialSail = 223
'Public Const lightSail = 224
'Public Const MagLevLifter = 225
'Public Const Turbojet = 226
'Public Const Turbofan = 227
'Public Const Ramjet = 228
'Public Const TurboRamjet = 229
'Public Const Hyperfan = 230
'Public Const FusionAirRam = 231
'Public Const StandardThruster = 232
'Public Const SuperThruster = 233
'Public Const MegaThruster = 234
'Public Const LiquidFuelRocket = 235
'Public Const MOXRocket = 236
'Public Const IonDrive = 237
'Public Const FissionRocket = 238
'Public Const FusionRocket = 239
'Public Const OptimizedFusion = 240
'Public Const AntimatterThermal = 241
'Public Const AntimatterPion = 242
'Public Const OrionEngine = 243
'Public Const SolidRocketEngine = 244
'Public Const Hyperdrive = 245
'Public Const JumpDrive = 246
'Public Const WarpDrive = 247
'Public Const TeleportationDrive = 248
'Public Const SubQuantumConveyor = 249
'Public Const ContraGravGenerator = 250
'Public Const HotAir = 251
'Public Const Hydrogen = 252
'Public Const Helium = 253
'Public Const ThrustBomb = 257
'Public Const QuantumConveyor = 258
'Public Const TwoQuantumConveyor = 259
'Public Const AerialSailForeAftRig = 260
'
'Public Const SimpleCustom = 1000
'Public Const GroupComponent = 1100
'
'Public Const PerformanceProfile = 999
